### ISSUE TITLE
Improve consistency between Tree Detail and Planter Detail dialogs

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#10]
Currently, planter details (and tree details on the Trees page) are shown on a side drawer, while tree details on the Verify page are shown as a modal popover dialog.

The two UIs could be more consistent.

![Screenshot 2020-10-02 at 16 18 31](https://user-images.githubusercontent.com/5558838/94940089-ed88c300-04ca-11eb-9058-dbc8379c37c2.png)

![Screenshot 2020-10-02 at 16 16 53](https://user-images.githubusercontent.com/5558838/94939906-b2868f80-04ca-11eb-99c2-ba15ae74f0e5.png)

**Comment by nmcharlton** [comment]
The `Drawer` component has a nice feel to it and works well for these sorts of detail dialogs.
A good first step would be to use a `Drawer` for the capture details, matching the planter detail layout (minus the image).
The _Close_ button can also be replaced with the _X_ used in the planter detail drawer.

The capture image could be centred on the remaining portion of the screen as a dialog with no need for padding, just a dark backdrop that ensures the image is in clearly visible and in focus:
![Screenshot 2021-07-18 at 19 44 22](https://user-images.githubusercontent.com/5558838/126078747-87586c07-c2bb-45a5-8e3e-3680c6597af0.png)

**Comment by chromium-52** [comment]
Is anyone currently working on this issue? If not, could I try this one?

**Comment by nmcharlton** [comment]
@chromium-52 Go for it!
