### ISSUE TITLE
Grower Detail: Display "About" description

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1030]
Each grower (`grower_account`) has a free-text `about` field.
This should be displayed in the Grower Detail dialog.

**Comment by DSY4444** [comment]
@nmcharlton can you please assign this issue to me. I think I can do it.

**Comment by nmcharlton** [comment]
Thanks @DSY4444. Let me know if you have any issues.

**Comment by DSY4444** [comment]
@nmcharlton can you please tell me where can I find admin login credentials after running app on localhost:3001

**Comment by nmcharlton** [comment]
@DSY4444 If you haven't done so already, you'll need to sign up as a Greenstand contributor here to get access to our Slack workspace. Once you're in, message me (@Nick - Admin Panel Lead) and I'll add you to the channel with credentials.

**Comment by andres039** [comment]
Hello, I think I have a working solution for this issue. May I share it as a PR?

**Comment by nmcharlton** [comment]
@andres039 Please do.
