### ISSUE TITLE
Edit Grower: Tidy up inputs

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1031]
Input fields in the Edit Grower dialog aren't very well aligned and spaced.
This dialog needs to be tidied up.

* There should be a space between _First Name_ and _Last Name_
* _About_ should span the full width like the other inputs
* _Grower-entered organization_ shouldn't be an input as it's never editable – it's just a prompt to help select the correct value from the _Organization_ dropdown.

<img width="528" alt="Screenshot 2023-02-21 at 19 17 41" src="https://user-images.githubusercontent.com/5558838/220438575-35a1fec9-6d5b-4bdd-a053-9d9425612c8e.png">

**Comment by Aditya-A-G** [comment]
hey, I would like to work on this. can 
@nmcharlton assign this issue to me

**Comment by Arc9067** [comment]
Hey, I will love to work on this, have you managed to resolve the issue?

**Comment by Aditya-A-G** [comment]
@nmcharlton do you know where I can find the admin panel login details?

**Comment by nmcharlton** [comment]
@Aditya-A-G I've added you to the Admin Panel channel on Slack. You'll find credentials in the pinned items.
