### ISSUE TITLE
Put an owner name for each token or tree and assign a name to each token 

### ISSUE THREAD

**Issue by TendryArivony** [Greenstand/treetracker-admin-client#1037]
In fact what we would like to do is to create a wallet for the customer who is a bank and then transfer their tokens to their wallet.
But for each token in their wallet, it must be assigned to a credit card, ie for each credit card it presents a tree.
So what we expect is that when we open the details of a tree there will be the name of the person who owns the card.

**Comment by sebastiangaertner** [comment]
@nmcharlton am closing this ticket.
