### ISSUE TITLE
Verify: Cannot reject a capture

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1046]
## Steps to Reproduce
1. Open _Verify_
2. Select a capture
3. Select _REJECT_ from the side drawer
4. Submit

### Current Behaviour
Rejection fails due to an incorrect URL root in the API call: `https://dev-admin.treetracker.org/undefined/raw-captures/:id/reject`

### Desired Behaviour
Rejection succeeds with a call to `https://dev-k8s.treetracker.org/field-data/raw-captures/:id/reject`
Note that the `field-data` URL is defined as the env var `REACT_APP_FIELD_DATA_API_ROOT`.

**Comment by SuspenseFallback** [comment]
Can I be assigned to this?
