### ISSUE TITLE
Grower Detail capture counts are incorrect

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1047]
## Steps to Reproduce
1. Open _Growers_ tool
2. Click any grower card to open the Grower Detail drawer
3. Capture counts (Approved, Awaiting, Rejected) are incorrect

### Current Behaviour
All growers show the _total_ number of captures in each state.
<img width="352" alt="Screenshot 2023-03-23 at 21 23 17" src="https://user-images.githubusercontent.com/5558838/227365962-6855fede-1c24-4b28-961d-064938be7890.png">

### Desired Behaviour
Capture counts only include captures associated with the grower displayed.

**Comment by andres039** [comment]
Can I give it a try?
