### ISSUE TITLE
Grower Detail: Full grower name is not displayed

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1048]
The _Grower Detail_ card should show the grower's full name as a header, but it has disappeared at some point and been replaced with a _First Name_ section.

### Current Behaviour
<img width="352" alt="Screenshot 2023-03-23 at 21 26 33" src="https://user-images.githubusercontent.com/5558838/227367375-80edc22d-49fe-4b93-bd21-e7ac63164c65.png">

### Desired Behaviour
<img width="352" alt="Screenshot 2023-03-23 at 21 26 23" src="https://user-images.githubusercontent.com/5558838/227367385-1523e5fb-3d24-4793-9751-7ac9b96d5b88.png">

### Changes Required
Reinstate the full name header and remove the _First Name_ section.

**Comment by andres039** [comment]
Hello, I would like to work on this issue
