### ISSUE TITLE
Grower Cards and Grower Detail: Organization is displayed incorrectly

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1049]
The _Organization_ section of the _Grower Detail_ drawer displays the wrong information for a grower's organization.

### Current Behaviour
* Organization name is not shown
* Stakeholder ID (UUID) is shown in brackets
<img width="352" alt="Screenshot 2023-03-23 at 21 30 54" src="https://user-images.githubusercontent.com/5558838/227368396-75e99c63-ec96-4fdd-88e4-eaa029eb3a7e.png">

### Desired Behaviour
* Organization name is shown
* Org `entity_id` (legacy org ID) is shown in brackets
<img width="352" alt="Screenshot 2023-03-23 at 21 36 25" src="https://user-images.githubusercontent.com/5558838/227369404-81457937-5cf8-4e32-a7fd-fe5ddeed0bc7.png">

Note that the grey, italic org name is the value entered by the grower and should be displayed if different to the confirmed org.

**Comment by nmcharlton** [comment]
We also see this bug in the Grower cards. It should be fixed there too.
<img width="204" alt="Screenshot 2023-03-26 at 16 45 41" src="https://user-images.githubusercontent.com/5558838/227787268-d16e2a89-82fe-4fad-ac60-b529aeeb98cf.png">

**Comment by nmcharlton** [comment]
Note that `entity_id` is not yet available from the stakeholder API. See Greenstand/treetracker-stakeholder-api#38.

**Comment by SuspenseFallback** [comment]
Can I be assigned to this?

**Comment by SuspenseFallback** [comment]
Can I be assigned to this?

**Comment by SuspenseFallback** [comment]
Can I be assigned to this?

**Comment by SuspenseFallback** [comment]
Sorry, my Github gave me an error message.
