### ISSUE TITLE
Grower Detail: Grower image not displayed

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1050]
The _Grower Detail_ card should show the grower image at the top, but is currently only showing the placeholder image, even when there's a valid grower image:

<img width="352" alt="Screenshot 2023-03-23 at 21 44 38" src="https://user-images.githubusercontent.com/5558838/227371087-971d018b-ac08-46db-b8bd-064ad129a668.png">

**Comment by SuspenseFallback** [comment]
I have posted a fix for this issue.
