### ISSUE TITLE
Edit Grower: Cannot update image rotation

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1051]
## Steps to Reproduce
1. Open _Growers_ tool
2. Select a grower card with an image
3. Click the edit button
4. Click the rotation button on the image
5. Click _Save_

### Current Behaviour
Update fails due to incorrect `imageRotation` parameter in POST.

### Current Behaviour
Admin Panel passes new value to the API as `image_rotation` and update succeeds.

**Comment by SuspenseFallback** [comment]
Can I be assigned to this?
