### ISSUE TITLE
Solver 404 error for these domains

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#1063]
When visiting https://dev-beta-admin.treetracker.org/login we got 404 error, but it is fine with https://admin.treetracker.org/login

Also, we need to solve these domain with the same problem:
dev-alpha-admin.treetracker.org
alpha-admin.treetracker.org
freetown-admin.treetracker.org
dev-freetown-admin.treetracker.org

**Comment by dadiorchen** [comment]
As we discussed in the community: https://greenstand.slack.com/archives/C8W6GT9MZ/p1680230765870219 this is a AWS job to set up the redirect for our CDN distribution

**Comment by emmanue** [comment]
Done.
