### ISSUE TITLE
Revert `REACT_APP_WEBMAP_DOMAIN` to main web map URLs

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#1070]
The v2 web map will shortly be migrated across to https://map.treetracker.org in production, as well as https://dev.treetracker.org and https://test.treetracker.org for dev and test environments respectively.

This means we can update `.env.development`, `.env.test` and `.env` to point `REACT_APP_WEBMAP_DOMAIN` at these URLs.

**Comment by SuspenseFallback** [comment]
Can I be assigned to this?
