### ISSUE TITLE
Update Capture Filter to allow filtering by either Grower Account Id or Grower Reference Id

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#1078]
Currently the filter only allows filtering by the grower_account_id.
Since we are limiting showing the uuids the filter should allow filtering by reference id.
It may be useful to allow filtering by either in the same field and then just check for if it's a uuid before making the api request.

**Comment by nmcharlton** [comment]
@gwynndp I like your suggestion that a user can enter either a reference ID or a UUID in the _Grower ID_ filter and the Admin Panel determines which field to query.

**Comment by nmcharlton** [comment]
I suggest we do the same in the _Verify_ and _Growers_ tools too.
