### ISSUE TITLE
CDN resize not working when planter image comes from DB directly (not AWS)

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#109]
See video 
https://youtu.be/V0g94Gc_5wE

**Comment by nmcharlton** [comment]
This is due to how we split the image url into `domain` and `file` to pass to Statically.
It works for AWS urls because they only have shallow paths. 
￼
For deeper paths like these, everything after the domain (`greenstand.org`) should be part of the `file` parameter.
