### ISSUE TITLE
No Messages, Yet  not in Portuguese or Swahili.

### ISSUE THREAD

**Issue by nprude** [Greenstand/treetracker-admin-client#1097]
1. Launch tree tracker app
2. Select the languages button on the upper right hand of screen. Select Portuguese or Swahili.
3. Hit the messages button
4. Select the profile button

Expected Result: "No Messages Yet" should be in Swahili or Portuguese.

**Comment by SuspenseFallback** [comment]
I think this is in the wrong repository?

**Comment by sebastiangaertner** [comment]
Yes this belongs in the android repro. https://github.com/Greenstand/treetracker-android
Please close this ticket
