### ISSUE TITLE
Add UUID to Verify filter and Capture Detail

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#110]
It should be possible to filter on a capture's UUID (`uuid` property).
Initially, this should be in the Verify tool, but #51 will align the Verify and Captures filters.
For consistency, the UUID should also be visible in the Capture Detail dialog (as a copyable item).

Currently there is no way to pull up a particular capture in the Admin Panel based on information in an image's file name (`TimeStamp-LatLong-UUID-OrigImageName.jpg`).
Date can be used, but this may pull up thousands of images.

**Comment by tranquanghuy0801** [comment]
@nmcharlton , for this issue, is that this will include 2 tasks below:

- Add UUID into the Capture Detail dialog
- Add new Filter field UUID in Verify tool 

Is this right? I am fixing the issue #51 so I can add these into that branch.

**Comment by nmcharlton** [comment]
@tranquanghuy0801 Yep, that's right.
