### ISSUE TITLE
Captures do not load on /verify and home page

### ISSUE THREAD

**Issue by fwang2000** [Greenstand/treetracker-admin-client#1106]
**Steps to reproduce**

1. Open https://dev-admin.treetracker.org/verify
2. Log in as admin
3. Loading persists and shows no captures

<img width="960" alt="Screenshot 2023-09-03 143659" src="https://github.com/Greenstand/treetracker-admin-client/assets/61210395/9848ba6e-1ff2-4d58-840d-83c0d56aa9c5">

<img width="960" alt="Screenshot 2023-09-03 144559" src="https://github.com/Greenstand/treetracker-admin-client/assets/61210395/13644471-1d3c-4dde-9c23-e0a0d61ce353">

**Investigation**

1. Appears to trigger a 422 error with the message "'organization_id' must be an array".
2. I discovered this during a huddle, but the error only occurs on my end. The other person had 24 captures registered.

**Comment by fwang2000** [comment]
On further investigation, if I open the filters and click the reset button, the images will load the 24 images and show the number of captures, but clicking the apply button will only cause it to load persistently.

**Comment by APH1997** [comment]
I'd like to work on this issue

**Comment by ShimiRokach** [comment]
When you first load the http://localhost:3001/verify
the query include the organization_id params.
But when you press the rest button the query don't include the organization_id and the api is return json correctly,
Does this organization id is crucial ? It seems like the backend api dont know how to parse it as array.
If not crucial I can pull my code I solved it by removing from filter the :       organization_id: ALL_ORGANIZATIONS,

**Comment by ShimiRokach** [comment]
btw you have the same issue here :http://localhost:3001/growers

because organization_id params is included in params
when you press the rest button the query don't include the organization_id params

**Comment by Kpoke** [comment]
Issue has been resolved

**Comment by SuspenseFallback** [comment]
Shouldn't this be closed?
