### ISSUE TITLE
Planter section. Need to be able to filter by Device identifier

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#116]
In order to see how many (and who) is using one device we need to have the device identifier in the planter search filter.

**Comment by nmcharlton** [comment]
Duplicate of #36

**Comment by nmcharlton** [comment]
The `device_identifier` is associated with the `planter_registration` record, not the `planter` directly.
Therefore we need a change to the API server to extend filtering beyond the LoopBack template.
