### ISSUE TITLE
Link to Planter id (currently still in webmap as userid) from each image

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#12]
See attached proposed design. Next to the location link (which does not work since the individual tree link https://github.com/Greenstand/treetracker-web-map/issues/178 ) we need a link to the userid such as https://treetracker.org/?userid=1868
![link-to-planter_id](https://user-images.githubusercontent.com/3283800/94421123-64e5ec00-0185-11eb-96c0-397edfcf0ff8.png)

**Comment by nmcharlton** [comment]
As part of this work, I'd suggest we turn these fiddly icons into chunky buttons that give the user proper feedback on hover and feel like something to be pressed.
We could include some text to make their function more obvious.

If we think it's too visually busy with four buttons on each card, we could have them appear/expand on hover, a bit like a [Material UI speed dial](https://material-ui.com/components/speed-dial/).
Suggestions are welcome.

**Comment by nmcharlton** [comment]
Also see #50, which converts all instances of tree ID and planter ID to webmap hyperlinks.
