### ISSUE TITLE
Ability to set the country when editing a planter

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#122]
Use case: During the verification process we often check the location of the tree and know the country. A simple drop down country list to assign the country to the planter would be a great addition. Same dialogue as the organization selector (edit planter)

**Comment by nmcharlton** [comment]
@sebastiangaertner We already have the capability in the Admin Panel to automatically populate the country of registration and display it in the Planter Details panel.
The missing link is a task in the Bulk Pack Transformer to populate the `geom` field in the `planter_registrations` table based on `lat` and `lon` (I'll raise an issue and get a PR created for that one).

We do not store this country value explicitly, but derive it on demand from the `geom` property.
This dropdown would only be appropriate if we want to track both of _country of registration_ (field data) and _assigned country_ (admin data), similarly to how we deal with organizations.

**Comment by nmcharlton** [comment]
Actually, the bulk pack transformer work has been done and is awaiting merge: Greenstand/bulk-pack-transformer#1

**Comment by rishad190** [comment]
I would like to start this part as a first issue solve

**Comment by nmcharlton** [comment]
Sorry @rishad190, I've only just seen your comment.

I think we need to discuss this issue a little more with @sebastiangaertner to clarify the issues I mention above.

This request is only valid if we want the ability to override/supplement the country/countries of registration with an _assigned_ country, or to use this input as a short-term fix before we get the bulk-pack-transformer fix in.

**Comment by sebastiangaertner** [comment]
@nmcharlton 
The needed usability addition is to show the country. If we get there through an automated process its great. In any case there is a great chance that a planter/grower can be in two countries although we can expect this to be the exception and can focus on the country of registration if that makes sense.

**Comment by gwynndp** [comment]
@sebastiangaertner @nmcharlton 
It looks like this is happening on the Grower Detail, so long as the planter was created since the API update and there is enough information to connect the planter registration to the planter table.

I tested using planter id # 937
Is there anything else that needs to be done?

<img width="921" alt="Growers - Treetracker Admin by Greenstand 2021-10-30 17-12-19" src="https://user-images.githubusercontent.com/1761374/139561732-c59a50f1-aaf1-4b59-9994-6966f6ca4077.png">

**Comment by nmcharlton** [comment]
@gwynndp I think this has been broken in the refactor - country is no longer included in the response.

Also, it doesn't look like the supporting bulk pack transformer changes ([PR 1](https://github.com/Greenstand/bulk-pack-transformer/pull/1)) have been deployed to test or prod - https://github.com/Greenstand/bulk-pack-transformer/actions/workflows/treetracker-api-deploy-test.yml

@ZavenArra Can we get this change deployed, at least to test?

We should also run a script against the DB to populate the `geom` column for existing planter registrations (which I realise now could have been part of the database migration that added the `geom` column).

**Comment by gwynndp** [comment]
@nmcharlton You're right, when I updated the query to include the device identifier I changed from '*' to 'planter-registration.*' which doesn't seem to work in this case.  I've fixed it and made a new PR.
