### ISSUE TITLE
Show country of registration in Planter details

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#13]
We should include the planter's country of registration in the Planter Details dialog.

![Screenshot 2020-10-02 at 16 10 05](https://user-images.githubusercontent.com/5558838/94939237-bfef4a00-04c9-11eb-8fc9-56c45dcb77f1.png)

**Comment by luacmartins** [comment]
@nmcharlton I would like to work on this.

**Comment by nmcharlton** [comment]
@luacmartins
We've discussed the relationship between `planter` and `planter_registration` a little more.

When a planter first uses a new device, a `planter_registration` record is created, which is then linked to the corresponding `planter` record (if one exists) by matching `email` or `phone` to `planter_identifier`.

There should be one `planter` record per actual person, but there may be multiple `planter_registration` records if they track trees on multiple devices.

We want to show information about all of their registrations, including if they're tracking in multiple countries.

#36 is related to this.
We could also update the _Registered_ date displayed to show the earliest registration.
