### ISSUE TITLE
Replace Rematch and Redux with React Context

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#131]
Rematch is proving a barrier to new developers understanding the Admin Panel code.
We should remove the tool and instead use React Context for shared state management.

**Comment by thejoshcooter** [comment]
The amount of data that we are working with in the app may potentially make a context only solution unwieldy, or the complexity of a context only solution could start bordering on simply using Redux itself. I can see it potentially creating issues and bottlenecks down the road.

New developers may be able to more easily work with Redux and hooks, as hooks are more familiar code to newer React devs. Even if they have never worked with Redux before, as far as access to state is concerned it is easy to teach them the pattern of getting slices of state from the store to work with.

Just some thoughts on addressing potential tech debt up front.

**Comment by nmcharlton** [comment]
Thanks @thejoshcooter, that's a really useful insight. We'd love to get more of your input on this activity.
Would you mind taking a look at the draft PR (#118) and adding your comments? @gwynndp is leading the work on this.

The key aim of this activity is to move away from Rematch, but it there's a good case to be made for holding onto Redux, or a particular pattern that suits our use case we're open to suggestions.
