### ISSUE TITLE
Grower Detail: Show number of captures

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#132]
The Planter Detail dialog should show the number of captures by the planter in each of the following states:
- Approved
- Awaiting Verification
- Rejected

There should be some visual consistency here with the Verification Status labels that can be seen in the Capture Detail dialog:

![Screenshot 2021-07-10 at 17 26 10](https://user-images.githubusercontent.com/5558838/125169841-ed2cff00-e1a3-11eb-93ae-908af023df40.png)
![Screenshot 2021-07-10 at 17 25 48](https://user-images.githubusercontent.com/5558838/125169831-df777980-e1a3-11eb-854b-be64a8dd7969.png)
![Screenshot 2021-07-10 at 17 26 26](https://user-images.githubusercontent.com/5558838/125169849-f5853a00-e1a3-11eb-9c3f-f0112ec4a161.png)
 

~~Clicking each number should show the corresponding captures in the Verify tool (by setting the Verification Status and Planter ID filters to the appropriate values).~~

**Comment by nmcharlton** [comment]
Here's the current dialog:

![Screenshot 2021-07-10 at 17 28 52](https://user-images.githubusercontent.com/5558838/125169918-4d23a580-e1a4-11eb-967b-6a74c497c0b4.png)

**Comment by nmcharlton** [comment]
UI design:

![image](https://user-images.githubusercontent.com/5558838/129452492-cbd626c2-df55-4430-b6dc-c9d4cd0473bd.png)

**Comment by tranquanghuy0801** [comment]
@nmcharlton , can I work on this issue?

**Comment by tranquanghuy0801** [comment]
![Screenshot 2021-09-08 at 00 06 50](https://user-images.githubusercontent.com/29462498/132358870-e98a9c25-2d6c-4713-8d9d-dadf2419913a.png)

This is my work with static numbers given. I will update them with the captures data to make it display exactly.

**Comment by nmcharlton** [comment]
Sorry @tranquanghuy0801, I've been offline for a few days and have only just seen this.
@thejoshcooter has been working on this issue – I didn't realise I hadn't assigned it.

**Comment by tranquanghuy0801** [comment]
@nmcharlton. that's alright, thanks for letting me know.

**Comment by nmcharlton** [comment]
@tranquanghuy0801 Do you still have a branch with your implementation of this issue?
If so, it would be great to revive it and finish off the implementation of the capture counts.

I'll split the link to the Verify tool into a separate issue as that adds a bit more complexity that we don't need immediately.

**Comment by tranquanghuy0801** [comment]
@nmcharlton yes, I still have that. I can take on this issue if you would like. Thanks

**Comment by nmcharlton** [comment]
That would be fantastic! Thanks Harry.
