### ISSUE TITLE
Planter filter: Reset button and Apply on enter

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#133]
The filter in the Verify tool has two features that would be useful in the Planters filter:

1. A _Reset_ button that sets filters fields back to their default values (empty/null)
2. Pressing _enter_ triggers _Apply_

Verify filter:
![Screenshot 2021-07-13 at 08 31 18](https://user-images.githubusercontent.com/5558838/125410338-b417a900-e3b4-11eb-8808-f4e8b2c71415.png)

Planters filter:
![Screenshot 2021-07-13 at 08 31 36](https://user-images.githubusercontent.com/5558838/125410373-be39a780-e3b4-11eb-85cf-826070b096b9.png)

We should strive for consistency across these components.

**Comment by thejoshcooter** [comment]
@nmcharlton I can take care of this Nick

**Comment by thejoshcooter** [comment]
Open PR and comments [here](https://github.com/Greenstand/treetracker-admin-client/pull/134).
