### ISSUE TITLE
Difference objects between API data and React elements in Capture Matching

### ISSUE THREAD

**Issue by tranquanghuy0801** [Greenstand/treetracker-admin-client#135]
The sample data collected from Capture Matching API has the format below. However, in file `CaptureImage.js`, it does not call the right properties of this object data.

![Screenshot 2021-07-17 at 23 41 00](https://user-images.githubusercontent.com/29462498/126038911-2295494e-6d06-49bc-8f0a-9ca41f7037fd.png)

**Comment by sebastiangaertner** [comment]
Thanks for pointing this out. Does this also address the issue that the planter image is taken from the tree table rather than the planter table?

**Comment by nmcharlton** [comment]
@sebastiangaertner Are you referring to the planter image in the Capture Matching tool?
The source of this image is irrelevant for the Admin Panel client; it's up to the treetracker-api component to provide the appropriate plater image, but this APi is currently only implemented as a stub.

**Comment by nmcharlton** [comment]
@tranquanghuy0801 We need to make sure we fix this in the right place.
I believe the current Admin Panel implementation is consistent with [the v1 spec in the treetracker-api project ](https://github.com/Greenstand/treetracker-api/blob/master/docs/api/spec/treetracker.v1.yaml).

The onus is on `treetracker-api` to make the spec and the API consistent.
@arunbakt @ZavenArra What's your opinion on this?

**Comment by tranquanghuy0801** [comment]
it looks like the `treetrack-api `gives the consistent data with the v1 spec. I think the issue was caused by `CaptureImage.js `calling the wrong properties.
