### ISSUE TITLE
Planter details is missing device identifier and the filter as per #116

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#145]
Planter details panel on right side in the Planter section needs the Device identifier and then the link to the filtered device identifier view also see #116

**Comment by nmcharlton** [comment]
@sebastiangaertner Device identifiers have been added (#141) but not yet deployed to test and prod – I'll do that this weekend.
The changes can be seen on the dev admin panel (https://dev-admin.treetracker.org).

Regarding the link to the filtered view, would a copy button suffice for the moment?
The functionality to link to a filtered view from a dialog like this is a little more involved and requires some design consideration to avoid a messy implementation.

**Comment by sebastiangaertner** [comment]
A copy button is fine for now since i think we do not have the device identifier filter established in the Web map API yet or?

**Comment by nmcharlton** [comment]
> A copy button is fine for now since i think we do not have the device identifier filter established in the Web map API yet or?

@sebastiangaertner Do you mean the Admin Panel API? You're right that the filter is not implemented there yet.

If you mean the web map, does your original comment refer to showing the captures that correspond to the device identifier on the web map?

**Comment by sebastiangaertner** [comment]
It would be great to have it in the web map as well. Ideally this then should be shown with graphically different icons for the identifiers otherwise there is almost no use case for showing the filtered map.
