### ISSUE TITLE
Replace Greenstand logo png with svg or native text

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#150]
The Greenstand logo with text that appears at the top of the menu on the home screen and in the toolbar on some pages is blurry due to scaling.

![Screenshot 2021-08-14 at 17 18 06](https://user-images.githubusercontent.com/5558838/129452699-fd20d812-5904-459a-9826-27e91e402dac.png)

It should be replaced with a crisp logo (either by rendering the png as an svg or by creating the Greenstand part with a native text element).

**Comment by sebastiangaertner** [comment]
@nmcharlton could you work with this https://greenstand.org/fileadmin/08-logos/logo-greenstand-standard.svg

**Comment by nmcharlton** [comment]
> @nmcharlton could you work with this https://greenstand.org/fileadmin/08-logos/logo-greenstand-standard.svg

Perfect! Thanks @sebastiangaertner
