### ISSUE TITLE
Showing the user-entered organization name in the Edit Grower dialog

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#158]
![Screenshot 2021-09-19 at 15 02 23](https://user-images.githubusercontent.com/3283800/133926793-460d3871-af54-454d-9fa1-2102c25d631d.png)

As you can see here in the picture the org is assigned so the drop down is showing the correct value. The name of the org is only available in the list view. It should also show in the edit view so you can compare the two. So a person might be entering "FCCYARC7A" which should be visible in the edit panel.

**Comment by nmcharlton** [comment]
Ideally, this addition would visually distinguish the _planter-entered organization_ from the _assigned organization_ in a similar way to that proposed in #88.

**Comment by ZavenArra** [comment]
This issue is heavily related to display of all grower sessions, and can't be resolved until the UI for session display is designed and implemented.

**Comment by nmcharlton** [comment]
In the meantime, we can do a quick fix for this to just display the `organization` we have available in the Grower object (the value entered by the grower when they signed up).

For now, it's needed as a visual check when selecting the corresponding Organization from the dropdown.
