### ISSUE TITLE
Remove .env files

### ISSUE THREAD

**Issue by thejoshcooter** [Greenstand/treetracker-admin-client#160]
We should remove all .env files from the repository and ensure that all secrets are stored securely.

**Comment by sunnyjain15699** [comment]
Would like to work on it, Can you guide what needs to be done ?

**Comment by nmcharlton** [comment]
Sorry @sunnyjain15699, I'm going to close this issue as we're currently following React best practice as described in https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env
