### ISSUE TITLE
Extending filter to work with parts of the string

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#162]
When filtering planter names first name or last name it would be great to 
1. not be case sensitive
2. find anything with that string contained (eg. LIKE '%seba%' )

in order to find Names easier

**Comment by gwynndp** [comment]
Similar to: https://github.com/Greenstand/treetracker-admin-client/issues/151

**Comment by Mloweedgar** [comment]
@gwynndp would like to work on this. I will dive into the code-base to see what I can do, in case of questions I will reach out to you

**Comment by Mloweedgar** [comment]
@sebastiangaertner can you assign this one to me?

**Comment by Mloweedgar** [comment]
@gwynndp do we have api documentation that describes how to filter/search using regex. 
 
to fix the above issue, I have discovered that we can use regular expressions in constructing the filters(the where object)

I have attempted the following approaches in using regex in the firstName field with no success:

1.  `{ firstName: {"$regex":  '/.*Assa.*/'}}`
2. `{firstName: '/.*Assa.*/'}`


Do you have any idea on this?

**Comment by gwynndp** [comment]
The api is built with Loopback, and I think we're on version 2:
https://loopback.io/doc/en/lb2/Where-filter.html#regular-expressions

**Comment by dadiorchen** [comment]
@sebastiangaertner does '%like%' require some setting up for the full-text search index on PostgreSQL

**Comment by nmcharlton** [comment]
@gwynndp @Mloweedgar For info, we're on version 4 of LoopBack
