### ISSUE TITLE
Remove blank space beneath the Verify page toolbar

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#170]
As of version 1.22.0, there's a gap at the top of the content area in the Verify tool:
![Screenshot 2021-10-11 at 22 08 27](https://user-images.githubusercontent.com/5558838/136856004-76a50369-1d23-4fac-909e-474fa17e2fe3.png)
This should be removed.

**Comment by lmpham1** [comment]
Hello! I'd like to give this issue a try. I noticed in the README.md that the credentials for test accounts are in your Slack channel. How can I join it? Or are there other ways to access the test credentials?

**Comment by nmcharlton** [comment]
Hey @lmpham1, that's great! [Here's the link to our Slack](https://join.slack.com/t/greenstand/shared_invite/zt-tm96d1id-7tLD7IC3nlGOdyV1aLzrSg).
If you'd like to get more involved with the project, you can fill our [contributor sign-up form here](https://docs.google.com/forms/d/e/1FAIpQLSdyLUffLPZZlHR-qfMwch5HkWcZ3kxM6h-eMK5PfGKLD4t8iA/viewform) and we'll arrange for you to be onboarded.

Let me know if you have any problems.
