### ISSUE TITLE
Alphabetically list the organizations on edit planter and filters

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#172]
When editing a planter it would be great to have the organization list alphabetically ordered. Currently its by id ASC

**Comment by nmcharlton** [comment]
The org query is implemented in this function: https://github.com/Greenstand/treetracker-admin-client/blob/edab59711f97283afdf3ec2b2799504c18566d4b/src/api/treeTrackerApi.js#L381

Organization selection in Edit Planter dialog:

![image](https://user-images.githubusercontent.com/5558838/142923070-b4e4ae35-c622-4656-8349-5c4392faa4f7.png)

Organization filter in Verify tool (same component as Captures tool filter):

![image](https://user-images.githubusercontent.com/5558838/142922736-549e99a1-ea4c-4386-bb5a-65d19cc29055.png)
