### ISSUE TITLE
Planter module: Easy way to determine if the app was Android or IOS

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#177]
with the IOS version coming in now we need a simple way to show that. This could be part of the planter profile. Theoretically a profile should be able to switch between operating systems and still get only one planter profile or?

**Comment by AlexCornforth** [comment]
If you need any client side changes to make this easier I'm happy to help.

**Comment by gwynndp** [comment]
@AlexCornforth -- Thanks!  
Do you already collect the userAgent info as well for the devices?
Or do you know of a way we could identify iOS from Android devices?
