### ISSUE TITLE
Display number of applied filters on all tools with filters

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#187]
The Verify tool has a badge displayed against the _Filter_ button that indicates how many filters are currently applied.
This should be replicated across the Captures and Growers tools for consistency.

![Screenshot 2021-11-04 211638](https://user-images.githubusercontent.com/5558838/140422132-fa1694cc-decb-4df0-b7c6-a3240d15de03.png)

Note that the same feature will be part of the new Earnings/Payments tools.

**Comment by gwynndp** [comment]
I'm thinking of integrating this into the refactors I've done so that I can include the badge in the FilterHeaders instead of on the main component.
