### ISSUE TITLE
ALL dates need to be uniform DD-MM-YYYY 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#190]
It is very confusing to filter by 6/1/2020 and its actually filtering 1st of June.

**Comment by nmcharlton** [comment]
@sebastiangaertner The Admin Panel should be using the format from your locale everywhere (DD-MM-YYYY in Tanzania).
Where are you seeing the MM-DD-YYYY format?

**Comment by sebastiangaertner** [comment]
I can not actually recreate the issue. Strange.

**Comment by nmcharlton** [comment]
We'll monitor this; I think I've seen it too in the past where the locale isn't always picked up correctly. There might be a race condition somewhere.
