### ISSUE TITLE
Add capture tags to Captures list

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#193]
We need to be able to see species, tags and other information in the list.

**Comment by nmcharlton** [comment]
As of v1.25.1, we have the following in the Captures list:

- Capture ID
- Grower ID
- Device Identifier
- Planter Identifier
- Verification Status
- Species
- Token Status
- Created (date and time)

The only information visible in the Capture Details that's missing from the list is the other tags:

- Morphology
- Age
- Additional tags
- Capture approval tag
- Rejection reason

**Comment by tranquanghuy0801** [comment]
For this issue, do we add new tags as a new column in the Captures list or do we only put them in Capture Detail dialog?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 We want them in the list too. They should already be in the Capture Detail dialog (but are missing at the moment due to #220).

**Comment by tranquanghuy0801** [comment]
@nmcharlton Can I work on this issue?
