### ISSUE TITLE
Additional Statistics for organizations

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#197]
See screenshot (UX needs to be consistent). Simple statistics. Number of planters that are associated with the organisation and list of Organizations associated with the mother org. 

// sample SQL to get the associated orgs from the DB in this case 178 = FCC Freetown
// WHERE p.organization_id in (select entity_id from getEntityRelationshipChildren(178)) 
![admin-panel-stats](https://user-images.githubusercontent.com/3283800/141726796-c3388399-20de-4ad6-9781-24ceaaa0e4de.png)

**Comment by nmcharlton** [comment]
@dadiorchen Is this in line with the dashboard statistics you're working on?

**Comment by nmcharlton** [comment]
@sebastiangaertner Can this be closed now that Freetown have their new dashboard with additional cards?
Do we expect to roll the new dashboard out to all users?

**Comment by sebastiangaertner** [comment]
@nmcharlton yes should roll out the stats as Freetown has them to all org users.
