### ISSUE TITLE
Create admin user role for earnings tool access

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#203]
Create admin user role for earnings tool access

**Comment by nmcharlton** [comment]
Only users with the `manage_earnings` or `list_earnings` policies in their roles should have access to the Earnings tool in the menu.

**Comment by nmcharlton** [comment]
@Mloweedgar Can you include this in your Earnings development?

**Comment by Mloweedgar** [comment]
Yes @nmcharlton , I will include them in the earnings tool

**Comment by nmcharlton** [comment]
@Mloweedgar We also have `list_payments` and `manage_payments` policies
