### ISSUE TITLE
Full capture details not loaded in Capture Detail dialog

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#220]
When a user opens the Capture Detail dialog (by clicking the tree icon in the _Verify_ tool or a row in the _Captures_ tool), the Admin Panel should load the full capture details, including tags and species.

![Screenshot 2021-11-29 at 19 36 16](https://user-images.githubusercontent.com/5558838/143931791-5df5ae2d-b5ad-48fe-907f-2fbdf404dcc3.png)

**Captures**
In the _Captures_ tool, Species and Additional tags are missing.
The client appears to query the capture but not these additional details.
![Screenshot 2021-11-29 at 19 48 50](https://user-images.githubusercontent.com/5558838/143933019-6508e3dd-5245-4ccb-a328-9c83c7649922.png)

**Verify**
In the _Verify_ tool, all of the "Other" tags are missing, as well as Species and token status.
The client does not query the capture at all.
![Screenshot 2021-11-29 at 19 41 44](https://user-images.githubusercontent.com/5558838/143933175-a4c06e08-141a-4ceb-96a9-eb5f4d287d54.png)

I can see a couple of things causing this:

- We're not wrapping these views with `CaptureDetailProvider` tags
- We don't return `capture` from `CaptureDetailContext::getCapture()` so it can't be passed to subsequent queries

**Comment by tranquanghuy0801** [comment]
@nmcharlton  can I take on this issue?
