### ISSUE TITLE
Improve capture multi-selection UX in for batch verification

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#233]
Currently, when a user wishes to select multiple captures in the Verify tool to perform a batch approval/rejection/tagging (a very common use case), they must either:

- Select the first in a range, hold shift and select the last (range selection); or
- Hold the ctrl/cmd key and select each capture individually to add to the selection

The second of these in particular is a clunky experience for the user. When holding ctrl on Windows and trying to scroll, the browser can zoom in and out instead. Therefore, the user has to release the ctrl key to scroll, making it more likely they'll accidentally select another capture without the ctrl key held and inadvertently clear their original selection.

There is also no feedback on the number of captures selected for batch processing.

![image](https://user-images.githubusercontent.com/5558838/144755002-cab0c723-a850-461a-829a-fbcd712bc228.png)

The following improvements should be made to the UX:

- Display the number of captures selected
- Always display the selection checkbox for captures to signal that clicking the capture will check/uncheck the box
- Clicking a capture should toggle its selection, rather than replacing the existing selection

Here's an initial design for the UI:
![Admin Panel - Bulk Select Captures - Greenstand-v01 01-1](https://user-images.githubusercontent.com/5558838/144755368-cb29ed90-a5c1-4db5-b622-2766ce67e5b9.png)

I'd suggest that the _Selected Captures_ dialog go above the _APPROVE | REJECT_ switch as it applies to both options.

**Comment by tranquanghuy0801** [comment]
@nmcharlton can I work on this?

**Comment by tranquanghuy0801** [comment]
@nmcharlton To confirm, is that clicking Select All / Unselect All button only toggles the selections in the current page, right?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 That's correct
