### ISSUE TITLE
Home page: Show loading spinner on dash stats while they're loading

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#242]
I can take around 10 seconds for the stats on the home page to load in the production environment (over 1.5 million captures).
The user needs to see some indication that something is loading.

The simplest option is to show a `CircularProgress` spinner until the number has loaded.
![Screenshot 2021-12-12 at 21 13 12](https://user-images.githubusercontent.com/5558838/145729954-750b179e-170d-45b0-80ba-649c11b81c15.png)

These stats are implemented in src/components/DashStats.js and src/components/DashStat.container.js

**Comment by husain3012** [comment]
How can I join the slack channel for the admin credentials? I want to work on this issue.

**Comment by nmcharlton** [comment]
Hi @husain3012. Follow this link to join our Slack: https://join.slack.com/t/greenstand/shared_invite/zt-znxupeau-TTFOSso5QQnumw8zJv~cFg

Message me (@Nick - Admin Panel Lead) when you're in and I'll add you to the appropriate channel.

**Comment by husain3012** [comment]
The PR is up for sometime now, hopefully it passes your code review!

**Comment by nmcharlton** [comment]
Hey @husain3012. Thanks for your contribution. I should have some time to review your PR this weekend.
