### ISSUE TITLE
Commas are missing to describe thousands place

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#251]
Please always insert a comma to show the thousands, millions, and billions place in all numbers as a standard.  This card shows one example of a missing command.  A number like 1200 should also be rendered as 1,200.

![image](https://user-images.githubusercontent.com/364622/147166591-884d6b03-750e-492d-ace9-5d6447be9566.png)

**Comment by arcadioramos** [comment]
Hi @dadiorchen , I would like to give it a try to this but I can't login to check the app I see that the credentials are in a slack channel but idk how to get into that slack channel

**Comment by dadiorchen** [comment]
I will add you to that channle

**Comment by dadiorchen** [comment]
I have added you into the slack, also I sent you a email with the dev env credential

**Comment by nmcharlton** [comment]
@arcadioramos Thanks for picking this up. Make sure to use `countToLocaleString()` in src/common/numbers.js to ensure the correct separator is used in different locales.

**Comment by arcadioramos** [comment]
Thank you @dadiorchen @nmcharlton

**Comment by nmcharlton** [comment]
Fixed in #255
