### ISSUE TITLE
Grower statistics are wrong

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#252]
In this card we see that the total number of growers is 19, but the breakdown per sub-organization shows much higher (and incorrect) numbers.  In fact the total growers for Freetown is around 400, so these statistics appear to be fully incorrect.  The growers card is meant to show the number of unique growers overall for Freetown, and then broken down by sub-organization.  Each tree has a 'planter_id'.  This the references to the table 'planter' which contains the information about each unique grower account currently.

I am not sure if this is a backend or frontend issue.

![image](https://user-images.githubusercontent.com/364622/147166665-791d044f-1a58-4720-93ed-83b5f472e979.png)

**Comment by Kpoke** [comment]
I believe I misunderstood the number to mean the number of sub-organizations, not growers. I would make the required changes
