### ISSUE TITLE
Statistics cards are slow to load.

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#253]
When I visit the statistics cards, they are slow to load.  However, the statistics can only possibly change once a day, because the data in the reporting schema is only refreshed every 24 hours.  Please implement a caching strategy to speed up these statistics.  This could be done by mounting the reporting API in the admin panel CDN with a cache strategy, implementing caching on the API side, by using PGPool, or by pre-calculating the statistics when data is reloaded and storing those in the db.   The cache either needs to expire on it's own after the time when the data is reloaded, or it can be triggered from the automated job populate-reports-schema.py in treetracker-airflow-dags

**Comment by ZavenArra** [comment]
@Kpoke has added an on demand cache to the API layer

**Comment by nmcharlton** [comment]
@ZavenArra Are you happy this can now be closed?

**Comment by nmcharlton** [comment]
These stats still seem to be loading slowly, but that may be at least partially caused by #600.

**Comment by nmcharlton** [comment]
The related issues have been resolved and reporting cards are now loading quickly.
