### ISSUE TITLE
Dashboard Reporting Cards are too wide on smaller screens

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#254]
There seems to be something wrong with the breakpoint. This screensize should still have 3 columns ideally. (yes, am still working on a 13 inch 2012 Macbook Pro ;_)
![Screenshot 2021-12-23 at 20 53 06](https://user-images.githubusercontent.com/3283800/147276261-929c6dbf-bb30-4d48-9bc8-eea8322542da.png)

**Comment by dadiorchen** [comment]
admin panel: You need to upgrade your mac to solve this problem

**Comment by dadiorchen** [comment]
Where is the forth small card on the top

**Comment by nmcharlton** [comment]
> Where is the forth small card on the top

@dadiorchen The user doesn't have Grower manager permissions, so doesn't see the Grower card.

**Comment by nmcharlton** [comment]
For reference, native resolution for this display is 1280x800.

**Comment by mitia-anah** [comment]
Hello team,

I am going to work on this issue.

**Comment by nmcharlton** [comment]
You will need to log in as a user with the Freetown Manager role. When logged in as Admin, go to User Manager and Add User. Create a user with Freetown Manager (select the checkbox and click the right arrow to assign the role).
![image](https://user-images.githubusercontent.com/5558838/158536601-b2e7686c-18e3-4391-9a1b-ed1bf8d5ee61.jpeg)

Then set the password using the key icon next to the new user in the list. It will be at the bottom of the page. Make sure you copy the password before saving. 
![image](https://user-images.githubusercontent.com/5558838/158536834-3b333532-49bd-4083-aa82-8037cdad7af4.jpeg)

Then log out of Admin via the Account page and log in as your new Freetown user. You should see the new stats on the Home page.

Any problems, let me know.

**Comment by mitia-anah** [comment]
> You will need to log in as a user with the Freetown Manager role. When logged in as Admin, go to User Manager and Add User. Create a user with Freetown Manager (select the checkbox and click the right arrow to assign the role). ![image](https://user-images.githubusercontent.com/5558838/158536601-b2e7686c-18e3-4391-9a1b-ed1bf8d5ee61.jpeg)
> 
> Then set the password using the key icon next to the new user in the list. It will be at the bottom of the page. Make sure you copy the password before saving. ![image](https://user-images.githubusercontent.com/5558838/158536834-3b333532-49bd-4083-aa82-8037cdad7af4.jpeg)
> 
> Then log out of Admin via the Account page and log in as your new Freetown user. You should see the new stats on the Home page.
> 
> Any problems, let me know.

Thanks for providing this.

**Comment by mitia-anah** [comment]
@nmcharlton, is there any specific size that you would like me to use, or is it ok if I think about it by myself? 
Thanks in advance
