### ISSUE TITLE
Layout glitch: User Manager Operations column wraps

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#259]
The last column get wrapped/broken

![image](https://user-images.githubusercontent.com/5744708/147714067-50a72d9f-0334-4701-a705-024209f3876a.png)

**Comment by dadiorchen** [comment]
Oh, maybe that's because some of the column is too long

**Comment by Siddhant-K-code** [comment]
> Oh, maybe that's because some of the column is too long

yeah, we should reduce the left navbar width!

**Comment by nmcharlton** [comment]
Fixing (and potentially standardising) the width of the menu sidebar is covered under #198

**Comment by nmcharlton** [comment]
It's worth noting that just shrinking the menu won't _solve_ the problem, since it could still happen on a small screen. We should set a minimum width or wrap policy on the final column to prevent wrapping.

**Comment by Ny-Rianala** [comment]
I am going to work on this task! Thanks!
