### ISSUE TITLE
Filter by Organization ID

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#26]
We need to be able to filter by organization ID including the org. hierarchy.

**Comment by nmcharlton** [comment]
@sebastiangaertner Are you referring to the capture filter in the Verify tool?

The basic version of the organization filter was implemented in December under [PR #482](https://github.com/Greenstand/treetracker-admin-api/pull/482) (see dev deployment – https://d2m5zl0de9jrzz.cloudfront.net) buit has not made it into the test environment yet.

Currently, all orgs are listed, and selecting a parent org in the filter includes all child org captures:

![Screenshot 2021-02-24 at 21 28 27](https://user-images.githubusercontent.com/5558838/109068052-414cb080-76e7-11eb-887b-e1ed819b62bf.png)

We have a design for a more complex implementation that involves preset exclude filter configurations:

![OrgFilter (1)](https://user-images.githubusercontent.com/5558838/109069511-385cde80-76e9-11eb-8ad6-08404210ee99.png)

**Comment by gwynndp** [comment]
I'm looking into this!

**Comment by nmcharlton** [comment]
We need a way to distinguish planting organizations from other organizations in the entity/stakeholder table.
Only the former should appear in the organization filter.

**Comment by nmcharlton** [comment]
This will be resolved by showing only entities with `type='O'` (see issue #73).

**Comment by nmcharlton** [comment]
Resolved in #87
