### ISSUE TITLE
Captures module: Adding "notes" field to the csv export option list 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#264]
See screenshot. The notes field is very important for some organizations which is something i have just learned. Can we add the notes field to the list in the screenshot?
![Screenshot 2022-01-04 at 20 25 54](https://user-images.githubusercontent.com/3283800/148099185-b98b5605-1fc9-4250-903b-73cd45d7549d.png)

**Comment by nmcharlton** [comment]
@sebastiangaertner I think it would make sense to add the note to the table too for consistency.

**Comment by tranquanghuy0801** [comment]
@nmcharlton Can I do this task?
