### ISSUE TITLE
Optimized images (growers and captures) displays black bars

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#270]
There seems to have been a change in the way https://cdn.statically.io/img/ (used for dynamic resizing and caching of images) renders images that causes black bars to be displayed if the requested aspect ratio does not match that of the original image:
![Screenshot 2022-01-06 at 21 01 21](https://user-images.githubusercontent.com/5558838/148451445-6bbf8c5c-ec71-42bc-b801-6e720db4b5c7.png)
![Screenshot 2022-01-06 at 21 01 39](https://user-images.githubusercontent.com/5558838/148451481-ed29b6b5-2cab-4bc5-a257-f810f186de45.png)
We can fix this by only specify a width when requesting an image from statically.io.
See `src/components/OptimizedImage,js`.

**Comment by popietree** [comment]
I'm working on this
