### ISSUE TITLE
Remove whitespace in Species table

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#271]
For some reason, we currently pad the Species table with whitespace if there are fewer rows than the rows per page value.
We shouldn't – it looks weird and is counterintuitive.

![Screenshot 2022-01-06 at 21 19 59](https://user-images.githubusercontent.com/5558838/148453702-a4cef51d-f5d2-4360-a18f-4583f8280e6d.png)

**Comment by S0han** [comment]
i would like to help with this.
is there any specific information i must know to get up to speed?

**Comment by nmcharlton** [comment]
Thanks @S0han, that's great! I've sent you an invitation to our Slack. Once you're in, I'll add you to the appropriate channel with the dev login credentials.

**Comment by S0han** [comment]
ok
