### ISSUE TITLE
Fix vertical alignment of menu icons

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#282]
Icons in the main menu (src/components/common/Menu.js) are not correctly aligned with the text:
![Screenshot 2022-01-10 at 19 51 15](https://user-images.githubusercontent.com/5558838/148840438-ef625aa4-5b0c-4690-9f61-a669b2fa2411.png)

**Comment by Ny-Rianala** [comment]
I am going to work on this issue. Thanks!
