### ISSUE TITLE
Expanded reporting card dialog: Total is missing separator

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#287]
The total at the top of a reporting card dialog should have a separator, like the other numbers in the dialog:
![Screenshot 2022-01-14 at 18 18 10](https://user-images.githubusercontent.com/5558838/149565334-f4ccc1ae-3cd5-4eb5-b693-724c7e048ba3.png)

Note that these cards are only visible to users with a Freetown role.

**Comment by Ny-Rianala** [comment]
Hi all,
I am going to work on this task.
