### ISSUE TITLE
Captures: Tag and Organization filters do not work if multiple verification statuses are selected

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#288]
A recent change to the Captures filter introduced the ability to include results for multiple verification statuses at the same time.
Unfortunately, the way the query is implemented in the API does not properly support the `{where: {or: [] }` clause used by the client and tag/organization filters are ignored if multiple verification statuses are selected in the filter.

It may be best to address this in the API.

**Comment by tranquanghuy0801** [comment]
@nmcharlton Can I work on this issue?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 It looks like @gwynndp has fixed this under #301, so we should be able to close this issue (subject to some testing). Sorry for any inconvenience.
