### ISSUE TITLE
Dash Stats: fix card width and wrap on smaller screens

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#296]
The basic dash stat cards that appear on the Home page currently flex in width to fit the space provided.
This means that they look odd on big screens and the content falls out on small screens:
![Screenshot 2022-01-16 at 12 25 36](https://user-images.githubusercontent.com/5558838/149659877-d595fec1-d312-47f0-a370-105a403492e4.png)
![Screenshot 2022-01-16 at 12 25 43](https://user-images.githubusercontent.com/5558838/149659880-b977c8ab-6489-42ab-a783-8bc2a5e9c289.png)
Instead, a dash stat card should be a fixed width that accommodates the text and cards should wrap if the container is too narrow.

**Comment by Tiaraha-funny** [comment]
@nmcharlton We are going to fix this issue.
