### ISSUE TITLE
Captures: show loading indicator

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#297]
It can take several seconds for any records to appear in the Captures table, especially when a complex filter is applied.
We need to give the user feedback that loading has not completed, e.g., a spinner.

**Comment by mitia-anah** [comment]
Hi @nmcharlton,

Would you mind providing us with some clarification on this task, please? For us to know how it should be. 
As we can see in the User Manager table, there is a loading indicator before the table appears. So, is the Captures table also expected to have the same features?

**Comment by nmcharlton** [comment]
@mitia-anah That's right.

**Comment by mitia-anah** [comment]
@nmcharlton Thank you. We are going to work on this issue.
