### ISSUE TITLE
Readme : Development Environment Quick Start

### ISSUE THREAD

**Issue by hizem** [Greenstand/treetracker-admin-client#299]
I tried to install the project locally on my machine following your **Development Environment Quick Start** and I noticed something wrong in your Readme file, it was recommended to use **Node v12** using the **nvm tool** but when I tried to install the project using the **npm install** command I got a message indicating that at a version between 16 and 17 is needed to run the project, this requirement was defined in the package.json file.
<img width="855" alt="Screen Shot 2022-01-16 at 10 38 38 PM" src="https://user-images.githubusercontent.com/32454249/149679445-949babe4-c1e6-4bfa-8ecd-6eaa60ff3e12.png">
<img width="570" alt="Screen Shot 2022-01-16 at 10 38 52 PM" src="https://user-images.githubusercontent.com/32454249/149679449-7da7d1a2-05de-4cc3-b926-070c8cb8619a.png">
<img width="827" alt="Screen Shot 2022-01-16 at 10 38 59 PM" src="https://user-images.githubusercontent.com/32454249/149679453-ad8c45c5-9a95-45d3-a17e-289d0f4684b6.png">

**Comment by nmcharlton** [comment]
Thanks for spotting that @hizem. The README needs to be updated to reference version 16.

**Comment by hizem** [comment]
@nmcharlton I want to fix that as my first contribution, can you assign me the Issue please
