### ISSUE TITLE
Change all 'trees' terminology to 'captures'

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#3]
All references to 'trees' in any current admin panel feature should instead read 'captures'.  And 'tree' becomes 'capture'.

![image](https://user-images.githubusercontent.com/364622/102548945-3daa0700-4070-11eb-853a-c0a031944f5f.png)

**Comment by nmcharlton** [comment]
@AnitaNa Would you mind working on this one?
I'm afraid it's not very exciting, but it needs doing.

**Comment by AnitaNa** [comment]
@nmcharlton  Sure, will you please explain this issue a little more to me, as I am not able to understand what exactly I have to do?

**Comment by AnitaNa** [comment]
@nmcharlton I got it, Zaven explained it to me.
