### ISSUE TITLE
Species choices not appearing in admin panel's Verify page

### ISSUE THREAD

**Issue by camwebb** [Greenstand/treetracker-admin-client#323]
Just noticed that you cannot select a species either as a filter, or a new annotation, in the Verify module of the admin panel. I guess this is associated with Issue #307.

**Comment by camwebb** [comment]
Oops - seems it was only a momentary glitch. Species lists are back now.

**Comment by nmcharlton** [comment]
@camwebb This is normally caused by slow loading, or occasionally just a server error. I've raised #369 to help spot the former.
