### ISSUE TITLE
Capture Matching: Implement captures filter

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#326]
The user needs to be able to filter capture presented on the left side of the Capture Matching tool.

The design has a filter button next to the pagination control, and uses chips to show which filters are currently applied:
![Screenshot 2022-01-25 at 19 01 46](https://user-images.githubusercontent.com/5558838/151041814-1985a1a9-dbf6-4ae7-958d-a532b6ac8984.png)

Clicking the filter button should show a basic filter dialog, similar to that on other tools.

Regarding UI/UX, we should consider aligning the filter with that of other tools, e.g., Earnings.

**Comment by ZavenArra** [comment]
This also requires some extensions to the API

**Comment by ZavenArra** [comment]
@nmcharlton We'll need a spec for the UI, is that something you and Ben can crunch.  

Organization and data range are the top priority.

**Comment by ZavenArra** [comment]
Organization uuids are waiting a merge from this PR: https://github.com/Greenstand/treetracker-admin-client/pull/365

**Comment by dadiorchen** [comment]
Finished by #572
