### ISSUE TITLE
Upgrading Cypress to 8+ can bring some convenience in terms of mock pages.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#328]
I used the Cypress from another project to mock the capture matching tool page, (mock the API), by doing this it become easier to develop. like this video showing:

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-01-26%20at%209.31.48%20PM.mp4

**Comment by nmcharlton** [comment]
We're now on Cypress 9.5.0
