### ISSUE TITLE
Capture Matching: Show collapse/expand icon against candidate trees

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#335]
Users have the ability to collapse candidate trees that don't match or while they inspect others, and re-expand them in case they did so in error.

This is done with an accordion-style control on the candidate tree card using an button in the top-right corner:

![Screenshot 2022-01-28 at 21 21 24](https://user-images.githubusercontent.com/5558838/151623148-09fda48a-c754-45bf-9b1d-e415b62b0606.png)

**Comment by xxGreyscale** [comment]
### Hello I am new to open source contribution and I would love to start contributing to this problem if I may.
Thank you

**Comment by nmcharlton** [comment]
Hi @xxGreyscale, that would be great, thanks.
I've sent you an invitation to our Slack channel to get the development credentials.
