### ISSUE TITLE
Naming of CSV file

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#350]
(1) If no organization is selected in filter and NO date range is selected
{start_date}-{end_date}.csv
Where start_date is the effective date of the oldest earnings record being exported, and end_date is the effective date of the most recent earnings record being exported.

(2) If no organization is selected in filter and date range IS selected
{start_date}-{end_date}.csv
Where start_date and end_date come from the date range filter.

(3) If an organization IS selected
Prepend the organization name to the file name described above.

**Comment by gwynndp** [comment]
It seems a good idea to include the grower name in the report or in the title too for easier reference than the uuid.
