### ISSUE TITLE
Add button to bring in grower detail pane from right when clicked

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#356]
In the Earnings Tool, place a small info icon next to each grower name which then opens a grower detail pane just like the one in the Verify Tool to show all grower details.

Ideally this would be created as a modular component that could be reused across the admin panel.

**Comment by gwynndp** [comment]
We need some grower data that is valid in the treetracker-api / admin-api in order to fully test this is working
