### ISSUE TITLE
Capture Matching: Show Grower detail dialog when the user clicks the Grower

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#359]
When a user clicks the Grower profile at the top of the capture card, the existing Grower detail dialog should appear as a drawer on the right of the screen (as it does in the Growers tool).

**Comment by Tanvir-rahman** [comment]
Hello @nmcharlton. Is the issue still open?
In growers page, i am seeing details on click. Or are you referring to other screen?

**Comment by nmcharlton** [comment]
Hi @Tanvir-rahman. This is still open. It refers to the _Capture Matching_ tool rather than _Growers_.
I'd suggest holding off on this one for now. It will be easier once we've completed some other work to move all the tools across to our new microservices.

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton, can I work on this issue?
