### ISSUE TITLE
Capture Matching: Show Capture detail dialog when the user clicks the Capture info or image

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#360]
When the users clicks a capture, the existing Capture detail dialog should appear to give all related information.
This should happen when the user clicks:

- The capture information or image on the left of the screen
- A capture image for a candidate tree match on the right of the screen

**Comment by dadiorchen** [comment]
@nmcharlton do you mean we can reuse the details panel for a caputrue for this?
