### ISSUE TITLE
Species lists: Show loading indicator if loading has not finished

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#369]
It often takes a while for loading of the species list to complete at the beginning of a session in production.
During this time, the Species filter in the Verify and Captures tools just shows _All_ and _Not set_, the Species tagging option in Verify shows _No options_ and the Species page has an empty table.

To give the user peace of mind that the tool is still working, we should show a loading indicator in each of these places:

- Species table
- Verify tagging Species dropdown
- Verify filter Species list
- Captures filter Species list

**Comment by Ny-Rianala** [comment]
Hi @nmcharlton, 

Just to check if I understand the task. So the requirement here is to add a loading indicator to each one of the bulleted points above. Is that how it should be? Thanks!

**Comment by nmcharlton** [comment]
Hi @Ny-Rianala, that's right.

**Comment by Ny-Rianala** [comment]
Thanks @nmcharlton , I am going to work on it.
