### ISSUE TITLE
Improve HTML title for Treetracker Admin web pages

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#39]
The current title, **Greenstand - Tree Tracker**, is not very helpful and breaks the Greenstand communications guidance by splitting Treetracker into two words.

For consistency with the webmap, it should read **Treetracker Admin by Greenstand**

The title should also change dynamically with page changes, e.g. **Verify - Treetracker Admin by Greenstand**

**Comment by VLuisa** [comment]
I can take a look at this if no one is working on it already

**Comment by nmcharlton** [comment]
Fantastic, thanks @VLuisa!

**Comment by VLuisa** [comment]
@nmcharlton When is the CaptureMatchingFrame component loaded/used and would that be a reason to update the page title as well?

**Comment by nmcharlton** [comment]
@VLuisa Yep, that’s the Capture Matching tool. It’s mid-development, so is disabled by default using an environment variable in `.env.development`: https://github.com/Greenstand/treetracker-admin-client/blob/74a3be689e53d77af793533c5007c80110b77451/.env.development#L4

**Comment by VLuisa** [comment]
@nmcharlton Ah perfect that makes sense, thanks!
