### ISSUE TITLE
Use OptimizedImage in ImageScroller

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#40]
The `OptimizedImage` class compresses images to thumbnails of a more appropriate size.
The `ImageScroller` class (used by `EditPlanter` to display planter images) does not currently use `OptimizedImage`, so full-size planter images are loaded unnecessarily.

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton , please check my PR #78
