### ISSUE TITLE
Capture Matching: Indicate that candidate matches are all trees within 6m

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#407]
The Capture Matching tool should include an explanation of what constitutes a Candidate Match (perhaps from a _?_ with tooltip on the _Candidate Matches_ card). That is, any tree within 6m of the capture.

**Comment by mayankbucha** [comment]
Hi @nmcharlton, may I work on this issue next?

**Comment by mayankbucha** [comment]
As I need to login to the panel for this issue, so can you plz provide login creds.

**Comment by nmcharlton** [comment]
> As I need to login to the panel for this issue, so can you plz provide login creds.

@mayankbucha I'll add you to our Slack to get the credentials you need.

**Comment by mayankbucha** [comment]
Should I add tooltip like this?

![image](https://user-images.githubusercontent.com/47553721/155212074-f7cda63d-4772-4906-8f4c-ea28d9ea35fc.png)

**Comment by mayankbucha** [comment]
@nmcharlton, there was an error when viewing capture matching. We see the page for a second and then it throws an error. In api response there was both latitude as well as lat property (similar for longitude and lon) that was received in `candidateCapture` object. So I have changed `CandidateImages.js` as below. Should I commit it?

https://github.com/Greenstand/treetracker-admin-client/blob/1578b01388d36c07d29c2c790d3f7830a387a480/src/components/CaptureMatching/CandidateImages.js#L248-L253
to
```diff
+ <DistanceTo
+   lat1={capture.latitude}
+   lon1={capture.longitude}
+   lat2={
+     candidateCapture.lat
+       ? candidateCapture.lat
+       : candidateCapture.latitude
+   }
+   lon2={
+     candidateCapture.lon
+       ? candidateCapture.lon
+       : candidateCapture.longitude
+   }
+ />
```

**Comment by nmcharlton** [comment]
The tooltip looks good 👍
