### ISSUE TITLE
Mouseover Grower or Capture thumbnail for quick-look details

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#408]
Currently, a user has to click a Grower or Capture thumbnail to open the respective details dialog.
It would be helpful to have a quick-look version that presents key details about the item, triggered by a mouseover.

This should be appear everywhere there's a Grower or Capture preview in the Admin Panel, but should not get in the way of other tasks or cause an irritation.

**Comment by nmcharlton** [comment]
Something similar to GitHub's mouseover quick-look would be awesome.

**Comment by mayankbucha** [comment]
@nmcharlton may I work on this issue?

**Comment by mayankbucha** [comment]
@nmcharlton should quick-look tooltip have clickable elements?

**Comment by nmcharlton** [comment]
> @nmcharlton should quick-look tooltip have clickable elements?

That would be awesome, but it's not essential.

**Comment by mayankbucha** [comment]
@nmcharlton, for grower tooltip I have included name, email, phone, organization with image similar to github tooltip. 
![image](https://user-images.githubusercontent.com/47553721/159126907-4101241d-f0cb-4f60-98b7-8b6fb75f9204.png)

But for capture, verfiy and capture matching, I am not getting what to show on tooltip. 
For capture and verify nearly all the details are shown in the table.

**Comment by nmcharlton** [comment]
Hi @mayankbucha. This is looking really good.
For Captures, the important thing to include is the thumbnail of the image (using OptimizedImage).
For Verify, none of the information is displayed in the main tool, so the tooltip should include Capture ID, Grower ID, Grower Identifier, Created and Note.

**Comment by nmcharlton** [comment]
The Verify tooltip can also be used in Capture Matching
