### ISSUE TITLE
Include capture location in Capture Details dialog

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#409]
We should display the lat, lon and country in the Capture Details dialog.
For the latter, I'd suggest separating out the `Country()` function in CaptureImage.js into a common component: https://github.com/Greenstand/treetracker-admin-client/blob/11af7be348eb9ba9a8c496fcc0defd3da30367ea/src/components/CaptureMatching/CaptureImage.js#L13

**Comment by Okwonks** [comment]
Hey @nmcharlton, I would like work on this. Can I take it up?
