### ISSUE TITLE
don't throw error when no earnings row present

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#410]
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-03%20at%2010.28.20%20AM.mp4

**Comment by dadiorchen** [comment]
This problem is partially because of the backend, but, for the front end, we need to handle 500 error and display some feedback for our users.

**Comment by dadiorchen** [comment]
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-05%20at%2010.30.13%20AM.mp4

**Comment by dadiorchen** [comment]
@ZavenArra can you reproduce this issue now? I can't

**Comment by dadiorchen** [comment]
I think now this problem has gone
