### ISSUE TITLE
Capture Matching: Update Country query to use `latitude` and `longitude`

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#422]
The fields returned in a capture object by treetracker-api have changed so that `lat` has become `latitude` and `lon` has become `longitude`. The country lookup in the `CaptureImage` component needs to be updated to reflect this.

At the same time, we need to fix this:
https://github.com/Greenstand/treetracker-admin-client/blob/4498a21d77b7c02ab1647248df303a603a5da198/src/components/CaptureMatching/CaptureImage.js#L15

`'undefined'` should not be in quotes.

**Comment by mayankbucha** [comment]
Hi @nmcharlton, I would like to work on this issue.

**Comment by nmcharlton** [comment]
Hi @mayankbucha. Hold off for now, I'd like to do a little more investigation on the API side before we change the client.

**Comment by nmcharlton** [comment]
@mayankbucha Could you just fix the `'undefined'` bug?

**Comment by nmcharlton** [comment]
@mayankbucha Please go ahead with the full issue as described.

**Comment by MassiGy** [comment]
Hey there, I've looked up to the issue description, and from what I've understood, I wanna suggest that you remove the quotes
that wraps the  undefined value, cuz it is a valid data type in javascript.

In other words: 

```diff
- if (lat === 'undefined' || lon === 'undefined') { 
+ if (lat === undefined || lon === undefined) {  
```

**Comment by MassiGy** [comment]
And for the first half of the issue, concerning the latitude and the longitude bugs. I think all you need to know to fix the `CaptureImage`  react component is to do this :

```diff
- <Typography variant="body1">
-              <Country lat={capture.lat} lon={capture.lon} />
- </Typography>

+ <Typography variant="body1">
+              <Country latitude={capture.latitude} longitude={capture.longitude} />
+ </Typography>
```


I'am a backend developer, so I've never touched to react, but I think that this is the first obvious thing to do.
Hope that this will help.
