### ISSUE TITLE
Limit the file type when upload with the OS file explorer

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#458]
So we can limit users just choosing `cvs` type of files.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-03%20at%2010.28.20%20AM.mp4

**Comment by ZavenArra** [comment]
yep great idea.

**Comment by dadiorchen** [comment]
Just CVS file is selectable. 

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/5744708/156864763-434f564e-7096-41ea-b726-b8c68a47a11e.png">

**Comment by nmcharlton** [comment]
Should be CSV
