### ISSUE TITLE
Leave some padding at the bottom of earnings/payments page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#461]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5744708/156691079-1a2a7fd1-c42d-4814-812a-aee3079c5e8a.png">

Also, it should be able to scroll when the list is longer/higher than the page.

**Comment by hi-ma-ns-hu** [comment]
Hey, I want to work on this issue.

**Comment by dadiorchen** [comment]
@hi-ma-ns-hu thanks! I have assigned it to you!

**Comment by hi-ma-ns-hu** [comment]
Hi, if I'm not wrong, I've to work inside PaymentsView and EarningsView under src/views folder.

**Comment by dadiorchen** [comment]
Yes just give some space to the bottom

**Comment by hi-ma-ns-hu** [comment]
Hi, for now I'm not comfortable with react and hence I'm facing difficulties in finding route path for this page which is used in browser address bar. Can you please help me to get this path.

**Comment by dadiorchen** [comment]
@Mloweedgar can you two go through this issue together? 
This problem is annoying, I can not check the list below when they exceed the screen's height.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/157784540-01509f34-6e73-43cc-bce2-cc785186158a.png">

**Comment by dadiorchen** [comment]
@hi-ma-ns-hu take a look at my PR above, I have solved this problem, thanks for your contribution, you can take a look other tasks if you want!
