### ISSUE TITLE
Capture Matching: Improve vertical scrolling

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#47]
The vertical scrolling behaviour of the Capture Matching tool could be improved.
Currently, there are three nested vertical scroll areas:

1. Candidate tree images (`CandidateImage.js`)
2. Candidate tree frame (right half of `CaptureMatchingFrame.js`)
3. Whole page

We should avoid nested scroll areas.

https://user-images.githubusercontent.com/5558838/112377524-c83c7b00-8cdd-11eb-85cd-808a3a6c16f3.mov

Instead:

- The candidate tree images should not scroll (the whole image can be displayed in the thumbnail)
- The left and right sides of the tool should scroll independently, or better still, the capture image on the left should be resized to fit the height of the viewport (the `CaptureHeader` can be reduced in height to allow more room for the capture image)
- The scroll areas should be visually distinct to give the user a cue for what to expect

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton , can I work on this? And what user account should I use to access the "Capture Matching" page?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 The Capture Matching tool is enabled through an environment variable.
Create or edit the `.env.local` file in the root directory of your repo and add the following line:
```
REACT_APP_ENABLE_CAPTURE_MATCHING=true
```
Then run `npm start` and log in with the admin account.
You should now see the Capture Matching tool in the menu.

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton , do you know how to create the sample data for Capture Matching?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 There's should be some dummy data coming from dev treetracker API (https://dev-k8s.treetracker.org/treetracker/captures) but it appears to be down at the moment.
I'll get that sorted and let you know when it's back up.

**Comment by nmcharlton** [comment]
@tranquanghuy0801 The dev treetracker API is now up and running again. You should now see some dummy capture data coming through.

**Comment by tranquanghuy0801** [comment]
I checked the API and there are some captures data. But the Capture Matching page currently has error, could not access that.

**Comment by nmcharlton** [comment]
@tranquanghuy0801 Are you still looking at this issue? It's a fairly low priority so there's no hurry, but we can remove the assignment if you're not.

**Comment by tranquanghuy0801** [comment]
I think this issue depends on the #135 and I don't work in this currently. You can remove the assignment and I will work in another issue.

**Comment by pieroapretto** [comment]
[](https://dev-k8s.treetracker.org/treetracker/captures) is currently returning a 503 status on GET requests.

**Comment by nmcharlton** [comment]
@pieroapretto Apologies, @gwynndp is fixing this as part of wider work on the Capture Matching tool.
I've assigned it to her now.

**Comment by nmcharlton** [comment]
This has been partially implemented, but we're still missing some key improvements:

- The two halves of the page should be visually distinct
- The capture container on the left should scale to fit the viewport

Note that there is a related issue to reduce the size of the capture header (#315).
These could be tackled together.

Current implementation:
![image](https://user-images.githubusercontent.com/5558838/150867344-f450e680-9610-4c10-b12b-6bbcf79531ae.png)

Original design:
![image](https://user-images.githubusercontent.com/5558838/150867594-c05df819-baf8-443e-ad2a-aaa617295462.png)
