### ISSUE TITLE
Capture Matching: Make Capture and Tree UUIDs less prominent

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#48]
The new-style UUIDs are very cumbersome as card titles.
They could be made less prominent (e.g. smaller font) or removed from the UI altogether.

![Screenshot 2021-03-24 at 20 26 59](https://user-images.githubusercontent.com/5558838/112378816-49e0d880-8cdf-11eb-8fc5-e81defddcf4f.png)

**Comment by nmcharlton** [comment]
Here's the UI from the web map for inspiration:
![image](https://user-images.githubusercontent.com/5558838/150872531-302bb739-71ec-4d73-8f17-d09f93891a20.png)

**Comment by dadiorchen** [comment]
@nmcharlton I did some change on the this, did you see it? the thing is the ID get cut and omit some part, and there is a tooltip to show the whole thing. Do you think is good enough?

**Comment by nmcharlton** [comment]
@dadiorchen Yep, I think that works well.
