### ISSUE TITLE
Earnings page: should do some checking when submit.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#496]
Now can directly click submit button, and get some error.

All these two inputs are required, so should ask the user to fill in before submit.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-13%20at%2010.17.21%20AM.mp4

**Comment by Mloweedgar** [comment]
@dadiorchen  please assign this issue to me, I am working on it
