### ISSUE TITLE
Earnings page: should show the message from server.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#497]
Like this case:
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-13%20at%2010.21.19%20AM.mp4

**Comment by Mloweedgar** [comment]
@dadiorchen  please assign this issue to me, I will work on it

**Comment by dadiorchen** [comment]
@Mloweedgar thanks!

**Comment by dadiorchen** [comment]
@nmcharlton do we have some common utils/components for this? a alert dialog.
