### ISSUE TITLE
Show Version on admin Panel startpage

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#5]
See screenshot. We should show the version or Build number and or deplyment date
![showVersion](https://user-images.githubusercontent.com/3283800/99778763-2a655380-2b25-11eb-83b7-8cf45b6d27f0.png)
 of the admin panel (in case we have a functioning versioning) See mockup

**Comment by nmcharlton** [comment]
Fixed in #16
