### ISSUE TITLE
Make all capture IDs (tree IDs) and planter IDs links to webmap

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#50]
Everywhere we display a capture ID (currently referred to as tree ID), we should make the text a link to the web map displaying that tree:
```js
`${process.env.REACT_APP_WEBMAP_DOMAIN}/treeid=${id}`
```

Similarly, where we display the planter ID, we should link to the webmap displaying all of the planter's trees:
```js
`${process.env.REACT_APP_WEBMAP_DOMAIN}/userid=${id}`
```

These IDs are displayed in the following places:
- Tree detail (Verify page)
- Planters page
- Planter detail (Planters page and Verify page)
- Trees page

The user should see some indication that clicking the link will open the webmap, and the link should always open in a new tab.

**Comment by nmcharlton** [comment]
@sebastiangaertner Does this seem like an appropriate solution?

**Comment by VLuisa** [comment]
I can take a look at this one!

**Comment by VLuisa** [comment]
@nmcharlton Do you think something like this suits the need? Open to suggestions! (If yes I'll go ahead and apply it to the other places mentioned)

![image](https://user-images.githubusercontent.com/10137547/116999042-19f8fd80-acad-11eb-8d75-e2cf70d16407.png)

**Comment by nmcharlton** [comment]
@VLuisa That looks awesome.
I've shared it on Slack to get some opinions from our tame users.

**Comment by VLuisa** [comment]
@nmcharlton Thanks for sharing it there! I followed up with one another question there so leaving the PR as a draft until I hear back

**Comment by VLuisa** [comment]
Just heard back, so I'll leave it as it is!
