### ISSUE TITLE
Payment page->Detail panel->Log form: a bug

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#508]
On the payment page, filter by `calculated` , then do the payment log, the payment list can not be refreshed after submitting. and if do it again, the error: earning has been paid or canceled can not be displayed for the user (it's possible to lead to confusion for the user)

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-15%20at%2010.53.59%20AM.mp4

**Comment by dadiorchen** [comment]
@Mloweedgar do you think this one is easy to fix?

**Comment by Mloweedgar** [comment]
@dadiorchen I can fix that. please assign this issue to me

**Comment by Mloweedgar** [comment]
@dadiorchen I think this is not very difficult to fix.

**Comment by Mloweedgar** [comment]
Also I think there is another UX issue, the payments page is supposed to display paid earnings only. @ZavenArra you can correct me if I am wrong. my first suggestion is that we start by fixing the UX issue such that the payments page only displays paid earnings only. let me know what do you think @dadiorchen. **Note:** log payment form is not displayed in Earnings details if that Earning has been paid.

**Comment by dadiorchen** [comment]
@Mloweedgar I'm okay for both, we can also consider disabling the paid filter, but my feeling is that that's a more complicated job.
