### ISSUE TITLE
Earnings page->Detail page: display uuid/ID of earnings

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#509]
As we display in the csv:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/5744708/158299320-905bd402-7ef3-4c7b-a627-138b6c21bba2.png">

**Comment by Mloweedgar** [comment]
@dadiorchen I am just curious, why do we need to display uuid/Id of the Earning, what is the use case?

**Comment by dadiorchen** [comment]
I think ID is a good way to communicate and locate exact record for people.
