### ISSUE TITLE
Make Verify and Captures pages more consistent

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#51]
The Captures page has fallen out of sync with the Verify page.
The following steps should be taken to make these more consistent.

## Capture detail
Use the same Capture Detail popup for the two pages (the Verify one is best)

## Filters
Provide the same set of filters and filtering experience.
Ideally, this should be the same component with responsive sizing to adapt to top vs side layouts.
Again, the Verify filter is more appropriate (with a Reset/Clear button as proposed by @gwynndp in #38)

## Captures page columns
Change the columns on Captures to match the details listed in Capture Detail.

**Comment by nmcharlton** [comment]
See #10 for better Capture Detail dialog design

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton , can I work on this issue?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 Let me know if you think it's worth splitting this issue out into multiple issues to make it easier to implement part of it.

**Comment by tranquanghuy0801** [comment]
@nmcharlton 
I think there is no need to split this issue at the moment. If I struggle on any parts of this, I will let you know.

**Comment by tranquanghuy0801** [comment]
@nmcharlton, is that compulsory for making the Captures table have the same data as the Capture Detail dialog as there are a lot of data to fill in the Captures table?
