### ISSUE TITLE
Earnings & Payments: format the money amount correctly

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#510]
<img width="179" alt="image" src="https://user-images.githubusercontent.com/5744708/158300639-c3b80e66-af51-4b87-8563-457f1041c164.png">
With comma, like 1,000,000

**Comment by nmcharlton** [comment]
See:
https://github.com/Greenstand/treetracker-admin-client/blob/3f0ba86979b4dc8a28d639f3e77eaaa1834c9add/src/common/numbers.js#L1
