### ISSUE TITLE
Export Captures as csv

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#52]
The Trees page needs an Export button that exports all trees included in the current filter to a csv file.
Pressing Export should generate a popup dialog that allows the user to select/deselect the columns they'd like to include (all selected by default).
When the user clicks Export in the popup dialog, the browser initiates a download of the generated csv file (including column headers).

Note that all filter matches should be included, not just those visible on the current page.

**Comment by nmcharlton** [comment]
@AnitaNa Take a look at https://github.com/react-csv/react-csv

**Comment by nmcharlton** [comment]
This has now become a higher priority task as an interim solution to allow Freetown (and other organisations) to perform analyses on their trees.
The first step is to generate a simple design of the UI/UX and the output.

**Comment by nmcharlton** [comment]
Need to consider number of records and possibly allow user to limit, or chunk up exports in multiple files.

**Comment by nmcharlton** [comment]
Proposed UI design:
![Screenshot 2021-07-16 at 17 45 31](https://user-images.githubusercontent.com/5558838/125981467-d6c01c8b-9f46-4416-b0f4-615ed402e734.png)

User workflow
1. User applies a filter to reduce the captures list to those of interest.
2. User clicks _Export Results as CSV_ button  –>  _Export Captures_ dialog opens.
3. User unchecks the checkboxes of any fields they do not wish to include in the download (all checked by default – to be reviewed when number of fields increases).
4. User clicks _Download CSV_  –>  client queries fields from API with filter set (in chunks if count too large) and triggers download using [react-csv](https://github.com/react-csv/react-csv).
5. Admin Panel provides feedback to user on progress if query is slow or chunked.

**Comment by tranquanghuy0801** [comment]
@nmcharlton can I work on this issue?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 It's worth checking with @vivek92-tech to see if he's made a start on this issue
We were discussing it during the team co-working session last week and suggesting that he could pick it up.

If possible, it might be good to try to collaborate on the issue.

**Comment by nmcharlton** [comment]
We're going to implement a proper, separate periodic reporting mechanism using Airflow and CKAN that will provide a managed data access model for organizations, outside of the Admin Panel.

The capability described in this issue should give the user a "quick and dirty" way of exporting the data they see in the results. Therefore, we could limit the number of records exported if the queries are too slow or the amount of data being served is too large.

**Comment by tranquanghuy0801** [comment]
@nmcharlton As the columns of Captures page are changed in issue #51 . Should I update the "Download CSV" button to have the same columns to it?

**Comment by nmcharlton** [comment]
> @nmcharlton As the columns of Captures page are changed in issue #51 . Should I update the "Download CSV" button to have the same columns to it?

Yes. Ideally, the list in the dialog should be populated from the list of columns, so that if someone adds a column, it automatically gets included in the dialog.

**Comment by tranquanghuy0801** [comment]
@nmcharlton , after we remove the Captures filter on right side, where should we put the button "Export Results as CSV" for this issue?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 For the upcoming Payments tool, @rgesulfo has proposed putting an _Export List_ button above the table, next to the filter button(s).

The design for that tool is slightly different to the current Captures tool (no toolbar), but I think we can do something similar.

![image](https://user-images.githubusercontent.com/5558838/135347582-2b3d8afa-3d92-4d8f-bddc-300ddcf39713.png)

It could go in the top right in the space above the table.

**Comment by tranquanghuy0801** [comment]
@nmcharlton, for downloading the Captures data, what is the maximum number of rows that you think we can put in the download functionality? As there are nearly 300K total captures, I think we cannot download all in once.

**Comment by nmcharlton** [comment]
@tranquanghuy0801 I proposed a limit of 10K to users, but the feeling is that's too low.
Are you able to try different limits (e.g. 10K, 50K, 100K, 500K) to see what the impact is as the size grows?
