### ISSUE TITLE
Add Tokenized to Verify/Trees filter and Tree Detail

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#53]
If a capture has a non-null `token_id` in the database, it is considered _Tokenized_.

We need to display whether or not a capture is Tokenized (in Tree Detail) and allow the user to filter on this value in the Verify and Trees pages (see #51 which aims to consolidate the filters on the two pages).

**Comment by nmcharlton** [comment]
This will require a supporting change in [treetracker-admin-api](https://github.com/Greenstand/treetracker-admin-api).

**Comment by VLuisa** [comment]
I can pick this one up!

**Comment by VLuisa** [comment]
@nmcharlton I'm less familiar with how Redux is set up in the app and how to go about adding in a new ajax request to get access to the token_id data (not sure if I'm even approaching this correctly) - mind giving me some pointers on how to get the right query for the token_id built in and where to do that? I'm wondering whether it makes sense to create two queries, one that looks for all null tokenIds and one that looks for all non-null

**Comment by VLuisa** [comment]
@nmcharlton Ah ok, makes sense. I was definitely overcomplicating it! Thanks!
