### ISSUE TITLE
Refine and restructure fields in Verify/Trees filter, Trees list and Tree Detail

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#54]
The fields currently displayed for a capture are basically mirrors of the database.
Instead they should display information in a format that is meaningful and logical for the user.

For example, we use two Boolean fields (`active` and `approved`) to denote the verification state of a capture:

- `active===true && approved===false` => Awaiting verification
- `active===true && approved===true` => Approved
- `active===false && approved===false` => Rejected

These should be combined into one _Verification State_ field for display and filter.

Data in the Tree Detail could be grouped by:

- Capture data (Planter ID, Planter Identifier, Device Identifier, Date Created, Note)
- Verification state
- Capture tags (Tags, Species)
- Tokenized

This will require some UI/UX design effort and input from @sebastiangaertner and other users.

Note that there are several other issues related to the Filters and Tree Detail: #10, #26, #29, #35, #37, #50, #51, #53

Current Tree Detail UI:
![Screenshot 2021-03-26 at 22 40 36](https://user-images.githubusercontent.com/5558838/112699678-49ce0d80-8e84-11eb-8168-78359390b4dc.png)

**Comment by nmcharlton** [comment]
> @nmcharlton I can take a look at this! I could start by making a rough mockup and soliciting some feedback

Awesome! Thanks @VLuisa.
As always, give me a shout if you need any clarification or assistance.

**Comment by VLuisa** [comment]
@nmcharlton Will do!
