### ISSUE TITLE
Be able to check the full size tree picture

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#567]
could be as simple as opening a new tab with URL of the image by clicking the picture.

**Comment by DJkal11** [comment]
It says the admin login details is in the slack chat but I'm not apart of it.

**Comment by dadiorchen** [comment]
Hey, @DJkal11 thanks for commenting here, please give me your email, I will invite you to the community

**Comment by DJkal11** [comment]
***@***.***

**Comment by dadiorchen** [comment]
Don't know why, can not check your email address, you can also send me message by dadiorchen @  outlook.com

**Comment by dadiorchen** [comment]
Duplicated with #360
