### ISSUE TITLE
Planter Manager cannot set planter selfie without Tree Manager role

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#57]
We query trees planted by the selected planter to get a set of selfies.
If a user with a Planter Manager role does not also have the Tree Manager or Admin role, the `trees` query will fail with 401 Unauthorized.

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton , can I have a look at this issue?

**Comment by tranquanghuy0801** [comment]
![Screen Shot 2021-05-02 at 12 26 08](https://user-images.githubusercontent.com/29462498/116800129-953da080-ab41-11eb-84ab-f34c4ba81a89.png)
Is this issue meaning that Planter Manager without Tree Manager role cannot use the filters in this screen?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 This issue refers to the images in the Edit Planter dialog you worked on in #78.

**Comment by tranquanghuy0801** [comment]
As I have seen from the web app, the images in the Edit Planter are fixed. You cannot edit to change those.

**Comment by nmcharlton** [comment]
@tranquanghuy0801 Sorry for the poor explanation of this issue.

It looks like we don't have many examples in the dev database, but if the planter has taken multiple tree captures, a planter photo will be associated with each capture.
We display each of these photos in the _Edit Planter_ dialog and allow the user to select from them.
In most cases in dev, there is at most one photo available, but in production there will be many.

Here's an example from admin.treetracker.org (with personal details redacted):
![Screenshot 2021-05-02 at 10 19 23](https://user-images.githubusercontent.com/5558838/116808288-e6449900-ab2f-11eb-8bde-891993b50d9e.png)

Try __planter ID 5338__ in dev. That has a couple of photos available.

To test, create a user for yourself with the _Planter Manager_ role but not _Tree Manager_ in the _User Manager_ tool.
Once you've created the user, you'll need to click the key icon to set the password before you can log in as that user.

**Comment by nmcharlton** [comment]
We need to figure out a better way of retrieving the `planterPhotoUrl` for each tree/capture associated with the planter without the need to query `trees` directly from the client.

The best option may be a new API endpoint under `/api/planters` (e.g. `/api/planters/:id/selfies`) that queries the trees controller directly on the server, bypassing the role authentication for the `/api/trees` endpoint.
