### ISSUE TITLE
The filter for organization can not unset correctly

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#575]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/5744708/159879684-52282cbf-5ad7-410c-9a78-09d47791e3d7.png">

So we can not clean this select for the filter

**Comment by DinahWorld** [comment]
Hi, can you assign me ?

**Comment by dadiorchen** [comment]
Sure, thanks!
