### ISSUE TITLE
Prevent user from creating a new species with the same name as an existing one

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#58]
Users can add species through the Species page or by tagging a capture with a species name they type in (rather than selecting from the dropdown).

Species names should be unique; if the name already exists, the capture should be tagged with that species.

**Comment by nmcharlton** [comment]
The species name matching should also be case-insensitive.

**Comment by tranquanghuy0801** [comment]
@nmcharlton , can I have a look at this issue?

**Comment by tranquanghuy0801** [comment]
![Screen Shot 2021-05-01 at 10 47 18](https://user-images.githubusercontent.com/29462498/116765841-9cde4600-aa6a-11eb-8a19-955ff2499aa7.png)
Hi @nmcharlton, for each capture at this page, is that multiple species can be tagged on the settings, right ?

**Comment by tranquanghuy0801** [comment]
Check my new PR #77

**Comment by nmcharlton** [comment]
@tranquanghuy0801 We can only assign one species to each capture or set of captures.
If a user types in a new species when tagging a capture, they are asked if they want to create a new species:
![Screenshot 2021-05-01 at 14 10 21](https://user-images.githubusercontent.com/5558838/116783513-f8b6c800-aa86-11eb-8f97-da54ee68c57b.png)
If what they've typed matches the name of an existing species (case-insensitive), we should use the existing one instead of showing this alert.

**Comment by nmcharlton** [comment]
Fixed in PR #77
