### ISSUE TITLE
The matching trees' layout is too crowded

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#587]
Should be able to scroll horizontally
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/5744708/160224026-87ff68ec-e152-4d53-add5-a935f0f7bdde.png">

**Comment by nmcharlton** [comment]
That's odd, horizontal scrolling used to work 😕 
I guess it got broken somewhere down the line.
