### ISSUE TITLE
Earnings & Payments: Use locale date format

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#596]
Throughout the Earnings and Payments tools we display dates in the MMM DD format (or some variation).
Instead, we should format dates according to the user's locale, as we do in the rest of the Admin Panel.

![Screenshot 2022-03-28 at 15 55 32](https://user-images.githubusercontent.com/5558838/160426309-51381c12-2180-4871-8bdc-1a72dc6ebfc4.png)

![Screenshot 2022-03-28 at 15 53 06](https://user-images.githubusercontent.com/5558838/160426095-31b280b9-5b50-4f38-a791-47bfbd47ee12.png)

**Comment by jeremydthomas** [comment]
Hey Nick, could you get me into the slack channel? Looks like I need login information that comes from there. @nmcharlton

**Comment by nmcharlton** [comment]
Hi @jeremydthomas, here's an invitation link: https://join.slack.com/t/greenstand/shared_invite/zt-13hedhs8w-fuQHV9S2yLuNs0Pm2sX4aA (valid for 24 hours).

**Comment by dadiorchen** [comment]
@nmcharlton I added this to the earnings milestone 2, please don't merge issues in m2 til we release the current earnings, to avoid new bugs, does this make sense?

**Comment by dadiorchen** [comment]
Maybe we need to develop a new workflow to deal with the concurrent dev branchs.

**Comment by dadiorchen** [comment]
Days before a volunteer formatted the money amount with commas, we ran into a new bug because of that...

**Comment by jeremydthomas** [comment]
Just seen this, was going to do a PR, should I just stop what I am doing for now @dadiorchen

**Comment by dadiorchen** [comment]
Yes, @jeremydthomas please hold on for a while, @nmcharlton I have another question now, I think in the earnings tool, we'd better use the date format in this way: yyyy-MM-dd, we can still use locale time, but the date format is like this.
The reason for this is that we need people to populate the date manually, I think the 2022-03-21 is easier than Mar 22, 2022, and this more clear to recognize in the excel

**Comment by nmcharlton** [comment]
@dadiorchen I agree. If we need consistency between what's in the CSV and what we display, ISO format is best.
Where we use locale format elsewhere, it's just to display system-generated dates/times and filter selections, so we favour human-readability over simplicity for parsing and avoiding errors, but as you suggest, this is a different use case.

**Comment by nmcharlton** [comment]
@dadiorchen I notice you've fixed the dates in the table under #634. It would be nice to still change the dates on the _Date Range_ button to use the locale format.
<img width="170" alt="Screenshot 2022-04-10 at 18 13 56" src="https://user-images.githubusercontent.com/5558838/162631348-60afa033-f06d-40c1-a3d6-8002dbb869a8.png">

**Comment by dadiorchen** [comment]
@nmcharlton what do you mean by `local format`? Is there any standard?

**Comment by nmcharlton** [comment]
See src/common/locale.js

**Comment by jeremydthomas** [comment]
Interestingly enough local.js is what I used in my changes. Was the easiest thing I seen to do without adding or changing too much to the codebase and what was used in other spots.

**Comment by jeremydthomas** [comment]
Did you want to look at my PR, I did use the local.js as it was what other modules were using.

**Comment by jeremydthomas** [comment]
@nmcharlton @dadiorchen did you guys want the changes using the locale.js format? i see the format got changed to yyyy-mm-dd. Ill just look for something else to work on if not.

**Comment by nmcharlton** [comment]
@jeremydthomas Let's leave this one for now. I'm happy that the change to yyyy-mm-dd introduces the consistency we need. I'll close the issue.
