### ISSUE TITLE
Dashboard stats missing on first load after login

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#61]
There appears to be a race condition with the first API calls following user login, whereby some calls have an undefined Authorization token in the header.

The result is some missing numbers on the dashboard.

Refreshing the page or navigating to another page in the Admin Panel forces a reload of the data, and subsequent sessions while the user is already logged in are fine.

**Comment by tranquanghuy0801** [comment]
Hi, Can I have a look at this issue?
