### ISSUE TITLE
The grower details panel is wrong

### ISSUE THREAD

**Issue by Tarek-Bohdima** [Greenstand/treetracker-admin-client#611]
~~Earnings page: export successfully.~~
~~- grower’s phone number in the CSV is different than that on the earning page and neither it does work on filter by grower’s phone number.~~

for this bug, check this video:

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-30%20at%203.49.39%20PM.mp4

Basically, we can not load the data of the grower correctly, and the traffic fetching data from API is huge (4m)

**Comment by dadiorchen** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5744708/160781616-4fa3181a-7f16-474b-a6ff-3c9da26e0e46.png">

**Comment by nmcharlton** [comment]
We can now support this functionality properly following the move to `/api/query/grower-account` for the GrowerDetail drawer, which supports the new grower UUID.
