### ISSUE TITLE
Missing column payments table

### ISSUE THREAD

**Issue by philnorc** [Greenstand/treetracker-admin-client#612]
According to testCases.md,
https://github.com/Greenstand/treetracker-earnings-api/blob/main/docs/test/testCases.md,
the payments table should have a column
"Count of captures"
Neither the test panel nor the dev panel have that column.
https://test-admin.treetracker.org/earnings
https://dev-admin.treetracker.org/earnings

**Comment by dadiorchen** [comment]
@philnorc because this is a bug of this repo, so I transferred it to here
