### ISSUE TITLE
Organization-specific Tags

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#620]
The list of historic Tags are taken from one pool which is confusing for admin panel users. There should be a pool of Tags coming from the organization or sub organizations

how to replicate: Verify -> Select a tree -> start typing in something = list of all historic Tags is shown.

**Comment by nmcharlton** [comment]
@sebastiangaertner I've moved this to the client project as we aren't doing any more changes to the legacy API.
This change will be supported in [treetracker-api](https://github.com/Greenstand/treetracker-api).

**Comment by nmcharlton** [comment]
The `owner_id` field was been added to the `tags` resource in treetracker-api under Greenstand/treetracker-api#85, but is not part of the legacy API. This should be set to the organization `uuid` from the legacy API or the stakeholder `id` once stakeholder-api is in use.

**Comment by nmcharlton** [comment]
Dependent on Greenstand/treetracker-api#89

**Comment by nmcharlton** [comment]
There are a couple more considerations for implementation:

1. For non-org (Greenstand) users, we need a way of indicating which organization a tag is owned by (e.g., a org name prefix in tag lists and chips).
2. As part of the tag migration from the legacy DB schema to treetracker-api, we will need to identify which existing tags should be marked as owned by a specific org and add an `owner_id` to those (after checking they haven't been used by any other orgs) and either duplicating any tags used by multiple orgs, or keeping them as Greenstand-owned tags.

**Comment by nmcharlton** [comment]
Assigning this to @Vlad-Pischaeff

**Comment by nmcharlton** [comment]
Hi @Vlad-Pischaeff. I notice that @gwynndp has addressed some of this issue in #832, namely setting `owner_id` for new tags to the org UUID of the current user. It might be best to hold off on your work until that PR is merged to minimise duplication.

**Comment by nmcharlton** [comment]
The API change is merged and this is ready to be worked on.

**Comment by nmcharlton** [comment]
@gwynndp In fact, is this already complete?

**Comment by gwynndp** [comment]
I think it just needed the owner_id to be used and that as we moved forward away from the legacy api the rest of the work suggested in this issue became obsolete.  Yes, I believe it's working to show tags by org on the site now.
