### ISSUE TITLE
Port OptimizedImage from Statically.io to new Greenstand service

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#621]
We've had some issues lately with [Statically.io](http://statically.io/), our image resizing/caching service for the Admin Panel. Rotation has been broken for some time and the service has recently stopped resizing images altogether, returning the original image after an initial 5s timeout period. A few issues have been raised on GitHub, but there has been little recent activity from the maintainer of the service.

Instead, we intend to build our own service to resize and cache images on the fly.
Once this has been implemented, we should move the Admin Panel across to it.

**Comment by iib0011** [comment]
Does this need need a new repo?

**Comment by nmcharlton** [comment]
> Does this need need a new repo?

We now have [images-api](https://GitHub.com/Greenstand/images-api).

**Comment by nmcharlton** [comment]
See spec: https://github.com/Greenstand/images-api/blob/main/docs/api/spec/images-api.yaml

The API is deployed in the dev env at https://dev-k8s.treetracker.org/images
This URL should be set in `.env.development`

**Comment by nmcharlton** [comment]
Note that the API supports rotation – we should replace our current CSS rotation with this mechanism.
