### ISSUE TITLE
Remove unnecessary warning logging from Reporting cards

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#622]
Some development logging has been left over in the dashboard reporting cards and can be removed:

![Screenshot 2022-04-03 at 14 23 00](https://user-images.githubusercontent.com/5558838/161430263-fe894e01-5a05-4903-b1b3-1430da56e09d.png)

**Comment by dadiorchen** [comment]
I guess that's from me, sorry, I planned to deescalate the log level to debug/trace so it will disappear.
