### ISSUE TITLE
Forget route when a user logs out explicitly

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#624]
Some of our users have more than one Admin Panel account (e.g., to support multiple organizations).
When a user logs out of one account (from the Account page) and logs in with another, they are redirected to the last page they were on (Account) which seems like odd behaviour.

When they log out explicitly by clicking _Log Out_, then log back in, we should redirect them to the home page.

Note that the redirection to the last page is desired behaviour on an _implicit_ logout (e.g., token expiry) to minimise disruption. This should be retained.

**Comment by rishad190** [comment]
@nmcharlton Could you please provide me with another admin account? I want to solve this routing issue.

**Comment by nmcharlton** [comment]
@rishad190 You can create an account for testing using the User Manager page. You will need to set the password for the new account using the key icon.

**Comment by rishad190** [comment]
@nmcharlton I believe the issue has been resolved. You can now look over the code.
