### ISSUE TITLE
Numeric values should be flush right

### ISSUE THREAD

**Issue by philnorc** [Greenstand/treetracker-admin-client#628]
In the Earnings and Payments tables, rthe columns with numeric values should be aligned flush-right, not flush-left. See Amounts and Capture Count.

**Comment by philnorc** [comment]
The column headings should also be flush right, else they are not above the numbers
<img width="463" alt="Screen Shot 2022-04-06 at 3 54 57 PM" src="https://user-images.githubusercontent.com/52667892/162069127-d61fdef1-f6ff-4a79-bfa5-d510bb9bac4e.png">
.

**Comment by dadiorchen** [comment]
@philnorc please check again, on the amount column, because of the sort icon need some space, so the right alignment of the header is not so perfect:

<img width="135" alt="image" src="https://user-images.githubusercontent.com/5744708/162149822-25056e15-3c40-430a-aea3-4569cdfbb02c.png">
