### ISSUE TITLE
Dashboard stats and trees do not update when logging in as a different user

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#63]
When switching accounts between a non-org and an org user, or between orgs, the data in the Admin Panel should be refreshed to match the new user.

Instead, stale data (dashboard stats, trees in the Verify tool) persists until the page is refreshed.

We should reset all Rematch models when logging out.

https://user-images.githubusercontent.com/5558838/114223303-8d864400-9967-11eb-85eb-d24a4ee35466.mov

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton, can I have a look at this issue?
