### ISSUE TITLE
Upload changes "paid_at" date

### ISSUE THREAD

**Issue by philnorc** [Greenstand/treetracker-admin-client#643]
After a batch upload, the table routinely displays a Payment Date one day earlier than the date specified in the uploaded data.

For example, I just uploaded two records with paid_at dates of 2022-04-07 and 2022-04-02.
The Payments table displays those two records with Payment Dates 2022-04-06 and 2022-04-01.

That is strange and bad. The user knows when he paid. We do not. We must honor whatever date the user supplies.

[upload.csv](https://github.com/Greenstand/treetracker-earnings-api/files/8437355/upload.csv)

**Comment by dadiorchen** [comment]
I think this is a pretty special case, when we upload the date, we just specify the date, not time, so when data is inserted into the db, we have to set it to the date + zero clock zero minitue, so if we use locale time to display the date, it's possible in some timezone the date number is changed, so we have to display the date in zero timezone, like I did in the PR.
@philnorc can you check now if the date are correct now on the page? You don't need to upload new file, just check the ones you made yesterday
