### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#656]
When I use my Chrome to login, (prod env) I got error:
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/5744708/166861294-72e4900e-0026-45da-94dd-f0cba6a91f69.png">

But if I use incognito mode, I succeeded:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/5744708/166861348-a5ba87b8-8b1a-44de-a75c-1ab818628728.png">

I guess this is because the `remember me` feature?

**Comment by nmcharlton** [comment]
This may be another symptom of #290. We may not be adequately clearing local storage when check_session fails, causing issues when you try to log in again.
