### ISSUE TITLE
Use different menu icons for Planters and User Manager tools

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#66]
We're currently using the same icon for the _Planters_ and _User Manager_ menu items.

![Screenshot 2021-04-14 at 11 59 18](https://user-images.githubusercontent.com/5558838/114699991-e31c7100-9d18-11eb-81e8-1bf00e36f15c.png)

A better fit for _Planters_ might be the Material UI `NaturePeople` icon:

![Screenshot 2021-04-14 at 13 30 24](https://user-images.githubusercontent.com/5558838/114710402-955a3580-9d25-11eb-87f8-704fa1e95b80.png)

**Comment by VLuisa** [comment]
Hi! I'm getting started contributing to open source and would love to pick this one up.

**Comment by nmcharlton** [comment]
Fantastic! Let me know if you need any help.

**Comment by VLuisa** [comment]
@nmcharlton I got a local build running and now I need the admin login details which I read are available on Slack; the current Slack link seems to have expired - think you can help me out with that? Thanks!

**Comment by nmcharlton** [comment]
@VLuisa You can use [this link to join our Slack](https://join.slack.com/t/greenstand/shared_invite/zt-3h4pdyth-p34LYlu3Pjg7UtEIWkWqag) (link valid for 24 hours).

If you'd like to contribute more, go to https://greenstand.org/contribute and click the _Join the tech team_ link. You'll be asked to fill in an onboarding form and will get a proper introduction to working with Greenstand. You'd be very welcome :smiley:

**Comment by VLuisa** [comment]
Awesome. I think I have a fix but haven't been able to find the admin login in Slack to test it out. I did end up signing up via the tech team link you sent, excited to keep contributing!
