### ISSUE TITLE
Capture tooltip doesn't show capture image and causes jumpiness

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#661]
Perhaps due to a merge problem, the Captures tooltip isn't showing a capture image.
Also, if you hover over a record towards the bottom of the screen, it causes the table to jump:

https://user-images.githubusercontent.com/5558838/169139526-4686d6f3-dbe6-4e1e-bac9-dbba86a5ad9d.mov

**Comment by mayankbucha** [comment]
@nmcharlton image is not shown because in `OptimisedImage` component (that we are using to display the tooltip capture image) the `cdnUrl`  that is generated is different from the `src` . And on accessing the `cdnUrl` we get 500 error.
