### ISSUE TITLE
Notes field should be visible for every tree in the capture matching tool (maybe even in other views)

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#667]
We have seen that the "notes" field in the app is often used to define if the capture is a first tracking or maintenance visit, therefore  it would make sense to show the content of the notes field in the capture matching tool. this could even be done with some kind of sticky note graphic and the notes content on that right on the image. https://media.istockphoto.com/photos/yellow-note-paper-picture-id459886461 as a sample. We can also extend the opacity based bottom part with the date and distance already displayed. 

In case of the capture matching tool this would give context that sticks out and can be used. Additionally the grower (and org or later contract) could be shown on the sticky note.

**Comment by nmcharlton** [comment]
For context, this is how we currently display an unmatched capture.
<img width="1552" alt="Screenshot 2022-09-16 at 21 34 40" src="https://user-images.githubusercontent.com/5558838/190728942-29778f5b-e986-416c-904f-8dfdcd203092.png">
In addition to the capture ID, time and location we need to display the contents of the `note` field for the capture (if not empty). This note is a string with no maximum length, but typical notes are up to 20 characters (see Captures tool in test env for examples).

This field typically contains a hint to the verifier/matcher such as whether the tree has been tracked before. We welcome design suggestions for displaying this information (such as the sticky note suggested by @sebastiangaertner). Note that we need to be careful when placing something over the capture image as it may hide a key detail for matching.

There are a few other changes proposed, including some additional information to support the matcher (see [comments on the Figma design](https://www.figma.com/file/G4Kl9fzLRgnk0SaeTne1Mc/Admin-Panel---Master?node-id=6255%3A3412)). The `note` design should keep that in mind.

## Candidate Matches
Each tree within a short range of the capture is displayed on the right hand side with each of its already-matched capture images. We need a tidy way of showing the `note` for those captures too.

**Comment by janet-yu** [comment]
Hello, I'd like to take a stab at this issue! I'm thinking if a note typically has <= 20 characters for a capture, then perhaps we can go the simple route and display it right below the image, similar to a caption or footnote.

**Comment by janet-yu** [comment]
Quick q: is there an example unmatched capture with candidate matches? I'd like to be able to tinker around with those as well.

**Comment by nmcharlton** [comment]
@janet-yu: @gwynndp and @Kpoke should be able to help – they're currently working on the data side of capture matching.
