### ISSUE TITLE
Unverified capture card can not be correct 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#668]
Attached the card showing 0 but when we filter by captures in the verify tool it shows 932 captures
![Screenshot 2022-05-23 at 20 48 46](https://user-images.githubusercontent.com/3283800/169886877-94d16497-8fad-4e19-a0a8-b181a9e76168.png)

**Comment by nmcharlton** [comment]
@sebastiangaertner @dadiorchen Can we close this one now? Data looks consistent from what I can see.

**Comment by nmcharlton** [comment]
Closing for now as this appears to have been fixed in treetracker-reporting.
