### ISSUE TITLE
Verify and Captures filters: Allow user to specify multiple grower IDs

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#673]
A common use case for the Verify tool is to approve captures from several growers at once.
In order to support this, the Grower ID filter should allow the user to specify multiple IDs.

For consistency, this functionality should be available in the Captures tool filter as well.

@sebastiangaertner Feel free to add comments if you have any.

**Comment by nmcharlton** [comment]
Hey @Tanvir-rahman. The Admin Panel API is built on [LoopBack 4](loopback.io), so queries use the `where` filter format defined [here](https://loopback.io/doc/en/lb4/Where-filter.html).

We have an open issue on the API (Greenstand/treetracker-admin-api#610) to make the LoopBack API explorer work with the custom Express auth layer.

It's not ideal, but you can browse the controllers (https://github.com/Greenstand/treetracker-admin-api/tree/master/src/controllers) to look for endpoints.

Note that this is our legacy API, so isn't being actively maintained. We're moving everything across to a set of microservice APIs that are much better documented.

**Comment by Tanvir-rahman** [comment]
Thanks a lot for the info. It was really helpful. Pushed the PR.
