### ISSUE TITLE
Capture Details: Allow user to remove capture tags

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#675]
If a user has the `APPROVE_TREE` policy, they should be able to remove capture tags, one by one, from captures via the Capture Details dialog:

1. Capture tag chips (the last ones listed under _Other_) are marked deletable for privileged users (X appears to the right of the label)
2. Clicking the X prompts _Are you sure you wish to remove {name} from this capture?_
3. User clicks _Remove Tag_ to confirm (_Cancel_ option also available).
4. Tag is removed from the capture by calling `DELETE /api/tree_tags/:id`.
5. Tag disappears from the list of chips.

<img width="1000" alt="Screenshot 2022-06-02 at 14 20 55" src="https://user-images.githubusercontent.com/5558838/171935880-6e7fc29a-f54a-4fbc-8ad0-eae68a7b5f75.png">

**Comment by a-marquez** [comment]
I've made healthy progress on the UI portion of this, I will create a draft PR for review and for questions I have.
