### ISSUE TITLE
Karen reports some duplicated trees showing up in the admin panel

### ISSUE THREAD

**Issue by Kpoke** [Greenstand/treetracker-admin-client#679]
![Image](https://user-images.githubusercontent.com/28721558/172466108-2eafed77-1737-4896-9cd1-bba574585229.png)

![Image](https://user-images.githubusercontent.com/28721558/172466314-9419b9ef-ad45-4772-ae6c-c3f46c6aa977.png)

The error might have to do with caching or with different user roles etc. But basically Karen is seeing duplicated trees on her end while Sebastian is not on his end

**Comment by nmcharlton** [comment]
Known issue in the API: Greenstand/treetracker-admin-api#609
