### ISSUE TITLE
Capture Detail: Show capture token ID

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#682]
In the Capture Details dialog we currently show _Impact token issued_ if the capture has have a valid token ID.
![Screenshot 2022-06-08 at 19 26 08](https://user-images.githubusercontent.com/5558838/172689906-815f9938-d6bc-471e-8b77-bfee06b31f01.png)

Instead, we should show the token ID itself with a copy icon, similar to Grower Identifier.
If no token ID is present, we should still show _Impact token not issued_

**Comment by Tanvir-rahman** [comment]
Hello @nmcharlton. I am looking into the issue. Will you please assign it to me? Thanks.
