### ISSUE TITLE
Species loading super slow (verify drop down and species module)

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#684]
Since the test data is only showing something like 5 species in production the scaling to 150 species creates some very long loading times. That is in the verify species drop down and also in the species list. 
In the species module list view the calculation of how often an id has been assigned slows it down. 
in the verify tool the drop down loads slowly because of ?????

**Comment by nmcharlton** [comment]
We run a single request to populate both lists.
Historically, it proved quicker to request the list of species and calculate capture counts in one request, but it hasn't scaled well, taking over 20s to complete for the 142 species we have now.

I think it may help to create an index on the public.trees table with `species_id` and `active` columns.

**Comment by sebastiangaertner** [comment]
That sounds good. 2 weeks ago we had only max of 80000 assigned species and now we have half a million

**Comment by nmcharlton** [comment]
This is being addressed in Greenstand/treetracker-database#104
