### ISSUE TITLE
Fix way of filtering for "All" values in Earnings Table filter

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#686]
This is a risky way of spotting that all values should be included.
If a user wants to filter by a grower name that starts with or contains "all", we will ignore the value and return all growers.

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/625#discussion_r889703220_

**Comment by Hengxin-Liu** [comment]
I will have a look tomorrow

**Comment by nmcharlton** [comment]
@Hengxin-Liu Have you been able to make any progress on this? Let me know if you need any help.

**Comment by Hengxin-Liu** [comment]
Yes I have already known the problem it is I will fix it on Thursday and Friday this week, sorry I am a little busy recently.

**Comment by nmcharlton** [comment]
No problem at all. Thanks for your efforts in this.

**Comment by pramodjsam** [comment]
![image](https://user-images.githubusercontent.com/33721221/209034284-02ec37d7-7e17-4381-be58-ba739e823b7d.png)

The way it is currently implemented is, if the grower name contains "all" along with other characters before or after, it returns all growers which contains that specific word. But if the growers name is "all", it returns all users. 

We cannot have both features, ie
1. Get all users by typing "all" into the search bar
2. Get the specific user whose name is "all"

**Comment by nmcharlton** [comment]
@pramodjsam Thanks for looking at this.
There's no desire to have the user type "all" in the search bar to include all growers. For this, they would leave the search blank.
The current implementation hard-codes the string for other filters when the _All_ option is selected from the dropdown, but the handler works the same way for all of them.

We should only handle the "All" case for dropdown filters, not free-text ones.

**Comment by pramodjsam** [comment]
@nmcharlton , Able to solve the issue by adding another check for growers while filtering
![image](https://user-images.githubusercontent.com/33721221/209455934-2ea86736-7d22-4dd4-8a58-d4b3be3ebd6b.png)

Now, while checking for "all" in the form, only the grower's name with "all" will be returned (if any)
![image](https://user-images.githubusercontent.com/33721221/209455941-1233c860-708e-493e-a06f-f32ee6480d7d.png)
