### ISSUE TITLE
Growers: hover popup doesn't go away when clicking on grower details

### ISSUE THREAD

**Issue by OGreeni** [Greenstand/treetracker-admin-client#695]
Hey, so I recently encountered this bug:

![image](https://user-images.githubusercontent.com/87455082/173960408-4b0a05a6-db06-4971-911d-51a7350d4159.png)

The hover popup on the grower profile persists even when clicking on the user's profile, which I believe isn't the intended behavior. The popup is still clickable and goes away once clicked.

**Comment by nmcharlton** [comment]
duplicate of #664

**Comment by OGreeni** [comment]
Currently working on a fix

**Comment by OGreeni** [comment]
Hey, submitted my PR
