### ISSUE TITLE
Account: change password modal shrinks on input

### ISSUE THREAD

**Issue by OGreeni** [Greenstand/treetracker-admin-client#699]
Before:
![image](https://user-images.githubusercontent.com/87455082/174464690-1d658e08-d633-4a8e-827d-b2c61d950250.png)
After:
![image](https://user-images.githubusercontent.com/87455082/174464695-f6ed4607-114a-47f9-8d0d-31caa8ee4ac2.png)

The modal returns to its original width once the field is cleared. This happens specifically with the "new password" field -- the other two don't experience this behavior.

**Comment by SuspenseFallback** [comment]
Is the expected behaviour to be wider or narrower?

**Comment by OGreeni** [comment]
I believe it should be wider. The password strength indicator is causing the issue.

**Comment by andres039** [comment]
Hi, I also would like to work on the issue if that's possible, thank you.
