### ISSUE TITLE
Organization users: 401 Unauthorized error for organizations query

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#70]
Organization users do not currently have permissions to list organizations, but the client is attempting to query organizations anyway.
In the short term, this query should be disabled for Organization users (to be implemented under this issue).

## Steps to reproduce

1. Log in to the Admin Panel as an organization user (a user with one or more organization-specific roles, e.g. Freetown Manager)
2. Open the _Verify_ page
3. Observe the 401 error in the console

![Screenshot 2021-04-18 at 17 25 46](https://user-images.githubusercontent.com/5558838/115152901-1e95a300-a06b-11eb-8a1c-0630429030c0.png)

In the long term, we will want to allow organization users to list and manage child organizations. This will be managed under a separate issue.

**Comment by gwynndp** [comment]
I ended up working on this on the server instead of the client.
https://github.com/Greenstand/treetracker-admin-api/pull/562
