### ISSUE TITLE
Edit Planter: User cannot clear planter organization

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#71]
In the _Edit Planter_ dialog, the user can select the planter's organization from a dropdown.
At the top of the dropdown list should be a blank option (meaning _no organization_).
This should set the planter's organization ID to null.

![Screenshot 2021-04-18 at 17 36 23](https://user-images.githubusercontent.com/5558838/115153219-b647c100-a06c-11eb-8513-302971779aff.png)
![Screenshot 2021-04-18 at 17 36 27](https://user-images.githubusercontent.com/5558838/115153218-b5169400-a06c-11eb-9920-a962a0b585d3.png)

**Comment by tranquanghuy0801** [comment]
Hi Nick, can I look at this issue? Regards, Harry

**Comment by nmcharlton** [comment]
Thanks @tranquanghuy0801, it’s all yours!
Let me know if you need any assistance.

**Comment by tranquanghuy0801** [comment]
Hi Nick,

So far I have inserted this code`<MenuItem value={null}>
                    No organization
                  </MenuItem>` into the option of field **organizationId**. However, the server returned the **422 Unprocessable Entity**. 

It seems like the server could not parse the null value. I don't understand why this issue happened as the field **organizationId** was set 'YES' for nullable property. Do you have any thoughts on this?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 This appears to be a quirk of LoopBack.
I did a bit of searching and came across https://github.com/strongloop/loopback-next/issues/2220#issuecomment-524567458.
It mentions adding the following inside the `@property` decorator, which seems to solve the problem:
```
jsonSchema: {
  nullable: true,
},
```
If you're happy to dive into the [API project](https://github.com/Greenstand/treetracker-admin-api) to make the change, I'll raise an issue to capture the work.

**Comment by tranquanghuy0801** [comment]
@nmcharlton  Yes I am also looking into the API to solve this.

**Comment by tranquanghuy0801** [comment]
@nmcharlton check my PR #75
