### ISSUE TITLE
Verify: Make gallery images taller

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#714]
The gallery view used in the Verify tool currently shows previews of tree captures as squares, with the middle of the image in the frame.
<img width="1552" alt="Screenshot 2022-06-30 at 20 08 05" src="https://user-images.githubusercontent.com/5558838/176759586-3a86851e-6f06-4d8d-8ec6-1dcae272a9e8.png">
In many cases, the subject of the photo is at the bottom, outside the centre square.
<img width="1552" alt="Screenshot 2022-06-30 at 20 07 47" src="https://user-images.githubusercontent.com/5558838/176759613-03aecd6c-556e-4470-ad2a-79e43e61deb8.png">
Since all captures are taken in portrait (as enforced by the Treetracker app) we should extend the previews to be taller and show more of the capture. A 3:4 ratio seems most appropriate.
<img width="1552" alt="Screenshot 2022-06-30 at 20 18 10" src="https://user-images.githubusercontent.com/5558838/176759997-650cac3b-0879-4342-b7a1-cec18ee08307.png">
<img width="1552" alt="Screenshot 2022-06-30 at 20 18 06" src="https://user-images.githubusercontent.com/5558838/176760012-1608d997-9cf2-4d8d-b254-d002756f3cc9.png">

**Comment by nmcharlton** [comment]
@sebastiangaertner What is your opinion on this proposal?
Would this be disruptive or helpful to the user community?

We could optionally make it another toggle, like the Small/Large image switch.
We could also make Small images the default so there's no loss in the number of images users see on one screen when they open the tool.

**Comment by nmcharlton** [comment]
Verifiers have requested that the whole image be visible in the preview card.
We have a mix of 3:4 and 9:16 portrait images coming in (depending on the device used) but need to show the whole image on the preview card in case there is something important round the edges that is missed during tagging. We need a design that accommodates both aspect ratios but offers a smooth visual experience. It may be as simple as empty space above/below shorter images, but I’m open to suggestions.
We may need to reduce the breakpoint widths for the small/large image toggle so we can still fit a sensible number of captures on the screen.

**Comment by OGreeni** [comment]
Hey @nmcharlton, an alternative would be to use a masonry layout. I.e. something like this:
![image](https://user-images.githubusercontent.com/87455082/184523221-4d54028a-45dd-419b-bda3-a1094d3128b7.png)

**Comment by nmcharlton** [comment]
@OGreeni That's an interesting idea. It would be good to trial it with users to see what impact it has on the verification workflow.

In particular, how well does it work for ordered sets like ours, and would it support range selection (shift+click)?

**Comment by muhon9** [comment]
@OGreeni masonry layout looks wonderful in image gallery and blog posts where order is not very important. Will it be a good idea for our purpose? Still we can have a trial and see the impact.

**Comment by OGreeni** [comment]
@nmcharlton yes, range selection would be quite difficult to implement with this layout. From a practical point of view, your initial idea of adding whitespace would work best.

**Comment by OGreeni** [comment]
@muhon9 I'm starting to second guess myself as this layout isn't very ideal for ordered sets. As much as it would create a seamless flow, preserving the order would be difficult.

**Comment by marwan-osama** [comment]
I want to work on this issue. I will try to change the aspect ratio of the card to fit 4:3 images by default and have white spaces to the left and right of the 16:9 images. is that ok?

**Comment by marwan-osama** [comment]
I want to work on this issue. I will try to change the aspect ratio of the card to fit 4:3 images by default and have white spaces to the left and right of the 16:9 images. is that ok?

**Comment by nmcharlton** [comment]
> I want to work on this issue. I will try to change the aspect ratio of the card to fit 4:3 images by default and have white spaces to the left and right of the 16:9 images. is that ok?

@marwan-osama That sounds good. Make sure to share a screenshot in the PR so we can compare.
