### ISSUE TITLE
Earnings tool: Add grower name and organization names to csv export

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#717]
Some additional information in the csv file should/could be: Planter names, organization name
![Screenshot 2022-07-01 at 11 07 57](https://user-images.githubusercontent.com/3283800/176853544-92ded7eb-b66c-4e35-b253-da457f3cc313.png)

Does the external processing mechaism have access to the API to get the planter name through the worker_id ? Is the worker_id representing the grower_id ?

**Comment by dadiorchen** [comment]
THese data come from stakeholder, you can verify it from the db, the work_id is stakeholder id, and the name is from stakehouler.first_name & last_name

**Comment by nmcharlton** [comment]
All of the required fields are available to the Earnings tool already. They just need to be added to the export.

**Comment by Kpoke** [comment]
Is the export making use of the API endpoint provided or is it completely handled on the frontend?

**Comment by dadiorchen** [comment]
head up:
1. This use the API to generate the export
2. The adding field is possible to impact the following upload operation. @Kpoke

**Comment by Kpoke** [comment]
@dadiorchen  we have to add those fields on the API side alone right?
