### ISSUE TITLE
Improve Account page styling

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#719]
The layout and styling of the Account page in the Admin Panel would benefit from some tidying up.
This would be a great task for someone with a keen eye for design.
<img width="1552" alt="Screenshot 2022-07-02 at 13 07 18" src="https://user-images.githubusercontent.com/5558838/177000110-cafe8d0a-8357-4815-81b9-4fae565eef53.png">

**Comment by FrancoFrancis** [comment]
would love to do that

**Comment by nmcharlton** [comment]
> would love to do that

Fantastic, thanks @FrancoFrancis! I've sent you a link to our Slack.

**Comment by FrancoFrancis** [comment]
ok awesome

**Comment by Rishabh770777** [comment]
Is it still open to contribution? I would love to help.

**Comment by nmcharlton** [comment]
Hi @FrancoFrancis – how are you getting on with this issue?

**Comment by nmcharlton** [comment]
@FrancoFrancis I'm going to unassign this from you so someone else can pick it up.
If you _have_ made a start, let me know.

**Comment by nmcharlton** [comment]
@Rishabh770777 Are you still interested in picking this up?

**Comment by FrancoFrancis** [comment]
> @FrancoFrancis I'm going to unassign this from you so someone else can pick it up. If you _have_ made a start, let me know.

@nmcharlton so sorry its taking me so long but im on it at the moment, made a start. Thanks for considering!

**Comment by nmcharlton** [comment]
No worries. Keep in touch as you make progress, share any designs you put together and consider opening a draft PR to update as you go along.
