### ISSUE TITLE
Captures: Include capture tags in export

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#720]
Currently, capture tags are loaded for captures in a separate query and are not included when exporting data since the export function only queries the `trees` endpoint.

In the long term, post-domain-migration world, we should include capture tags in the capture query API to limit the translation in the browser.

~In the short term, we could do the mapping at the same time as we currently map species IDs to species names, but should be wary of the impact on performance and potential for locking up the browser process.~

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton , can I work on this ticket?

**Comment by tranquanghuy0801** [comment]
<img width="1327" alt="Screen Shot 2022-09-20 at 11 05 42 pm" src="https://user-images.githubusercontent.com/29462498/191265480-2dd27200-36b1-4747-9cac-640a94fe2098.png">

Hey @nmcharlton , the `Capture Tags` still appears in the CSV export file after I download it. Is this the task of this issue?

**Comment by tranquanghuy0801** [comment]
@nmcharlton That makes sense. So the task is to fetch tag results in all pages?

**Comment by nmcharlton** [comment]
This has been fixed by the domain migration. Tags are included directly in the response to `GET /query/v2/captures`.
