### ISSUE TITLE
Growers: Add a public facing About field to the Grower

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#721]
Add an _About_ section for each Grower:

- Display the text in the _Grower Detail_ dialog
- Add a multiline text edit to _Edit Grower_ dialog (limited to 200 characters)

This issue has a dependency on the migration of the Growers tool to treetracker-api and the `about` field being added to that API (https://github.com/Greenstand/treetracker-api), but work on the UI can start with a stubbed out interface.

**Comment by nmcharlton** [comment]
- API dependency: Greenstand/treetracker-api#94
- Refactoring dependency: #680

**Comment by elyselam** [comment]
Assigning to myself

**Comment by sebastiangaertner** [comment]
Here is the new web map where the grower info will be shown 
https://prod-k8s.treetracker.org/web-map-beta/demo/top

**Comment by sebastiangaertner** [comment]
![Screenshot 2022-09-13 at 20 18 27](https://user-images.githubusercontent.com/3283800/189965853-36693e8c-b089-4ddd-a5bb-6d16bee53d31.png)
treetracker.grower_account.about
