### ISSUE TITLE
Stakeholders: Change "Not set" in filters to "All"

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#723]
'Not Set' may be a little confusing – we use it elsewhere to mean show only records with null/empty values in this field.

Make the default "All" instead

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/340#discussion_r889707958_

**Comment by tranquanghuy0801** [comment]
@nmcharlton can I work on this issue? Also, is that ok to just only remove the `Not Set` option in Stakeholder filters?

**Comment by nmcharlton** [comment]
@tranquanghuy0801 We just need to rename "Not set" to "All".
