### ISSUE TITLE
`first` and `second` might be `null` or `undefined` in Stakeholders Table

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#725]
`first` and `second` might be `null` or `undefined` here.

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/340#discussion_r896067278_

**Comment by tranquanghuy0801** [comment]
Is this issue occurring in file `Stakeholders/Table.js` ?

**Comment by nmcharlton** [comment]
> Is this issue occurring in file `Stakeholders/Table.js` ?

That's right.

**Comment by gwynndp** [comment]
This issue looks like it was resolved in #340.  Closing for now
