### ISSUE TITLE
Organization filter in tree verification not updating

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#73]
When i change an entity type in the DB from p to O or o to O or anything else it does not seem to reflect the filter. Can we only show capital O types?

**Comment by nmcharlton** [comment]
The simplest fix is to update the following API call to use `[type]=O`:
https://github.com/Greenstand/treetracker-admin-client/blob/ed20e83450e1ef617201290ef790708868b012d7/src/api/treeTrackerApi.js#L374

Note that there are other associated organization filter issues that may move this logic to the API side (#26, #37, #70).
