### ISSUE TITLE
If we're making this a delete function rather than unlink, let's use a trash icon.

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#730]
If we're making this a delete function rather than unlink, let's use a trash icon.
If deletion is just a placeholder for unlinking, can you add a comment to explain what's happening here?

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/340#discussion_r911393284_

**Comment by nmcharlton** [comment]
Also see #739
