### ISSUE TITLE
Stakeholders: Make child rows more visually distinct

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#731]
I think we need more visual distinction for child rows. Sorting in particular feels strange when child rows look more or less like their parents.

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/340#discussion_r911414916_

**Comment by nmcharlton** [comment]
Original design:
![image](https://user-images.githubusercontent.com/5558838/181909825-b5655096-a99d-4153-8544-8d471dfcc14d.png)

Current implementation:
<img width="1552" alt="Screenshot 2022-07-30 at 13 00 07" src="https://user-images.githubusercontent.com/5558838/181909843-fb6ee487-fe19-458f-ae74-00208775598a.png">

**Comment by marwan-osama** [comment]
I would like to work on this issue!
