### ISSUE TITLE
Captures: Include Wallet name if capture is tokenized

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#734]
When a _capture_ has an associated token, that _token_ is always assigned to a _wallet_.
The _wallet name_ will be added to the captures query API under a separate issue.

The wallet name should be displayed in the Captures list against the capture and _Wallet_ should be added as a filter.

**Comment by mayankbucha** [comment]
@nmcharlton can I work on this issue?

**Comment by nmcharlton** [comment]
@mayankbucha Absolutely!
