### ISSUE TITLE
Fix Capture Detail dialog appearance while loading

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#740]
There are a few minor issues with the appearance of the Capture Details dialog when first opened (from Captures tool):

- Copy buttons are taller than the text next to them, causing jumpyness when they first appear.
- Country field goes from _loading..._ to _Unexpected error_ to _loading..._ to _Country name_ to _loading..._ to _Country name_. It also flickers between _loading..._ and _Country name_ every time the panel re-renders.

https://user-images.githubusercontent.com/5558838/178161555-bbb785fc-4198-49a1-810d-411539413fe5.mov

Also, default values when capture data has not yet loaded are not great:

<img width="340" alt="Screenshot 2022-07-10 at 21 51 16" src="https://user-images.githubusercontent.com/5558838/178161710-3c4c2e5b-8a82-4607-984b-ecc9586613c8.png">

We should instead indicate loading, possibly with [skeletons](https://mui.com/material-ui/react-skeleton/) or a [spinner](https://mui.com/material-ui/react-progress/#circular).

**Comment by kasmediautamu** [comment]
Hello @nmcharlton , can I work on this issue?

**Comment by nmcharlton** [comment]
@kasmediautamu Yes please!

**Comment by mayankbucha** [comment]
@nmcharlton if this issue is still open, can i work on this?

**Comment by mayankbucha** [comment]
@nmcharlton country name glitch seems to be resolved by the above pr. But, I cannot figure out why the country name was getting rendered twice. And why `useMemo()` was used specifically only for the country name property.

**Comment by nmcharlton** [comment]
I believe @Vlad-Pischaeff has addressed the country issues in #798

**Comment by Vlad-Pischaeff** [comment]
My solution is better, I suppose.
My decision fixed cause rather then effect

сб, 27 авг. 2022 г. в 13:34, Nick Charlton ***@***.***>:
