### ISSUE TITLE
Captures download

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#744]
The Captures download has to include "lon", "lat" and the "image URL" in the exported data set. We are building a simple QGIS tutorial on how to use your data in a 3rd party program. In order to actually import a usable map we need the 3 additional fields. See attached this is the current data that is exportable. 
![Screenshot 2022-07-11 at 09 31 53](https://user-images.githubusercontent.com/3283800/178202657-60573995-3047-4964-888e-f9509ebe4f15.png)

**Comment by sebastiangaertner** [comment]
We will need this download/export to the base of a tutorial that explains how to get a QGIS map from that data.

**Comment by Mkhmalech** [comment]
it s done i will create pr soon
