### ISSUE TITLE
Add species name to Verify tool capture tooltip

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#746]
Users need to quickly see what species (if any) has been assigned to captures in the Verify tool.
If `capture.speciesId` is set, species name should appear in the quick-look tooltip that appears when a user hovers over the preview card (`CaptureDetailTooltip`).

Species name is available as a lookup from `speciesContext.speciesList`.
The Material UI `Category` icon should be used.

<img width="430" alt="Screenshot 2022-07-18 at 21 03 54" src="https://user-images.githubusercontent.com/5558838/179607561-647b8f25-232c-4748-ac09-3b896ccf45f9.png">

**Comment by FrancoFrancis** [comment]
would love to be assigned a new task to contribute to

**Comment by andres039** [comment]
Hello everyone, I think I have solved this issue, I just did a Pull Request, I hope it works. Thank you.
