### ISSUE TITLE
Add "Any species set" option to Species filter

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#747]
Users should be able to filter captures in the Verify and Captures tools to show only those captures that have had species values set. For consistency with the _Tag_ filter, this should be implemented as another option in the Species filter dropdown: _Any species set_

**Comment by daltbunker** [comment]
Hey could I get assigned to this issue? I believe I have a working solution for the 'Any' set in Captures. Looking into doing the same in Verify now.
