### ISSUE TITLE
Display capture `reference_id` instead of `id` across Admin Panel

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#769]
**Note: Branch from change-to-microservices**

Following the refactor to use the new microservices, the legacy `id` field is now called `reference_id`.
This is how Treetracker platform users refer to captures and should be displayed everywhere we have a capture ID.
<img width="1552" alt="Screenshot 2022-08-01 at 20 21 33" src="https://user-images.githubusercontent.com/5558838/182229167-2a8c689c-76a5-42c4-9d93-faf6caa23306.png">
<img width="1552" alt="Screenshot 2022-08-01 at 20 21 22" src="https://user-images.githubusercontent.com/5558838/182229188-0abc44a6-98c1-4cc2-a24a-8012eacb58e4.png">
<img width="1552" alt="Screenshot 2022-08-01 at 20 21 14" src="https://user-images.githubusercontent.com/5558838/182229198-8be21e88-b16e-4acd-a323-759a23f5ac1a.png">

**Comment by nmcharlton** [comment]
@gwynndp Did you say you've been working on this one?

**Comment by gwynndp** [comment]
Yes!  I updated the microservices branch first.  I'll work on this one today.

**Comment by gwynndp** [comment]
Looks like the work is done already.  The uuids still showing are grower account ids.
