### ISSUE TITLE
Capture Detail: Move URLs to client API layer

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#770]
URLs should be abstracted away from components in the API layer.
The Capture Detail dialog queries different APIs depending on where it's opened from, but currently, the containing components pass a URL to the `CaptureDetailDialog` component.

See https://github.com/Greenstand/treetracker-admin-client/blob/change-to-microservices/src/components/Verify.js#L739

Instead, they should pass something like an enum that is converted into a URL in the client API layer (`treeTrackerApi.js`).
This enum can also be used to determine the _mode_ of the dialog (how to present information about the capture).

**Comment by y-usuzumi** [comment]
Hi, I'd like to give it a try as my first issue, but I'm not sure I get what's the mode of the dialog. The `CaptureDetailDialog` components doesn't seem to have different modes in different places (currently Verify and Captures). Could you please elaborate a bit?
