### ISSUE TITLE
Captures: The export csv does not include Lat and lon yet

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#772]
The list has the lat and lon but not the export yet.

**Comment by nmcharlton** [comment]
@sebastiangaertner Where are you testing this?
Those fields are in the export from the beta environment for me.

**Comment by elyselam** [comment]
Please assign this to me

**Comment by elyselam** [comment]
<img width="2093" alt="image" src="https://user-images.githubusercontent.com/30991021/203474219-233735f5-6a56-47ae-a2da-10d093766e9c.png">
Am I looking in the right place? I see lat and lon in the csv download

**Comment by nmcharlton** [comment]
@elyselam Yes, you're right. `lat` and `lon` are included in the export.
I see the same behaviour in the production environment.

I'll close this issue as fixed.
