### ISSUE TITLE
Tidy reporting card titles

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#773]
Wording, capitalisation and pluralisation is inconsistent in reporting cards.

The following changes should be made:
* "Grower" -> "Growers"
* "total" -> "Total"
* "Average captures per grower per organization" -> "Average Captures per Grower" (per organization is implied)
* On Species card, "Total" -> "Count"
<img width="1552" alt="Screenshot 2022-08-04 at 20 57 22" src="https://user-images.githubusercontent.com/5558838/182941722-d468a4b3-fc6f-4e41-8244-df89c3f6657e.png">

**Comment by muhon9** [comment]
Will fix it

**Comment by nmcharlton** [comment]
> Will fix it
> 
> 

Sorry @muhon9, @jwardoin  managed to get the fix in quickly on this one.
