### ISSUE TITLE
Species: The `next page` button is invisible

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#785]
I don't if this just happens on my browser:

https://admin.treetracker.org/species

<img width="1440" alt="Screen Shot 2022-08-16 at 3 41 51 PM" src="https://user-images.githubusercontent.com/5744708/184825123-07ab497b-aca8-4f8b-84b9-4bce6cc6d426.png">

**Comment by marwan-osama** [comment]
It works fine in the local development environment.

https://user-images.githubusercontent.com/64364953/184851435-002c2caf-6ede-4bdc-99fa-159acaec282e.mp4

**Comment by nmcharlton** [comment]
Pagination only spans the first three columns, so is cropped when those columns are too narrow to accommodate it.
The problem is seen when species descriptions (forth column) are long and reduce the width of the first three columns.
This is the case in production, but not in development.

We need to give pagination controls more space.

**Comment by Vlad-Pischaeff** [comment]
![image](https://user-images.githubusercontent.com/48124219/185779061-fec0788c-f6ed-4f17-838f-1f301def3866.png)

I don't see the problem in dev

**Comment by Vlad-Pischaeff** [comment]
I suggest you use padding: 6px for better UI

![image](https://user-images.githubusercontent.com/48124219/185779423-a4bd9439-3771-4f04-8282-9b21eb270666.png)

**Comment by nmcharlton** [comment]
@Vlad-Pischaeff If you can't reproduce it easily, I'd recommend checking things like the browser @dadiorchen is using, what resolution produced this and if there are any hints in the code to why it might not work in all situations.

I'd also suggest using creating species with the same name and description as those seen in the original screenshot to see if that's a factor.

**Comment by nmcharlton** [comment]
The arrow is hidden for me on Chrome in dev:
<img width="1552" alt="Screenshot 2022-08-21 at 19 11 44" src="https://user-images.githubusercontent.com/5558838/185804975-900c64f1-431a-4ec3-8b3c-c1efbf50a41e.png">

**Comment by marwan-osama** [comment]
> Pagination only spans the first three columns, so is cropped when those columns are too narrow to accommodate it. The problem is seen when species descriptions (forth column) are long and reduce the width of the first three columns. This is the case in production, but not in development.
> 
> We need to give pagination controls more space.

yeah, I am able to see it now, I want to work on this issue.
