### ISSUE TITLE
Prevent species operations from wrapping

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#787]
The operation buttons against each species in the Species table can currently wrap if the column is narrow.
They should be prevented from wrapping (in the same way as the User Manager tool).
<img width="1552" alt="Screenshot 2022-08-21 at 20 24 12" src="https://user-images.githubusercontent.com/5558838/185807598-4bdb3f91-e550-45b6-800b-7a6baec5a657.png">

**Comment by marwan-osama** [comment]
I would like to work on this issue.

**Comment by dadiorchen** [comment]
Yes please!

Dadior Chen

在 2022年8月22日，12:33，Marwan osama ***@***.***> 写道：

﻿

I would like to work on this issue.
