### ISSUE TITLE
Captures: Prevent event bubbling

### ISSUE THREAD

**Issue by Vlad-Pischaeff** [Greenstand/treetracker-admin-client#797]
Сlicking a link "Open in new tab" (http://localhost:3001/captures)

![image](https://user-images.githubusercontent.com/48124219/186578877-deb1cd62-2b2c-4dc5-b12b-6cb265affaff.png)

causes a click event on a row

![image](https://user-images.githubusercontent.com/48124219/186579177-af2a2dae-327b-4814-9ada-75401146cdaf.png)

![image](https://user-images.githubusercontent.com/48124219/186579306-3405230e-fa82-4566-b19d-038c17d73128.png)

**Comment by mayankbucha** [comment]
I would like to work on this issue.

**Comment by Vlad-Pischaeff** [comment]
Ok
