### ISSUE TITLE
Compiling with problems

### ISSUE THREAD

**Issue by amesk3** [Greenstand/treetracker-admin-client#802]
![image](https://user-images.githubusercontent.com/12309592/187009626-ab5cda9e-75e9-4236-8fff-f9ed00e0abce.png)

While onboarding on the Admin panel UI side, I followed the documentation on onboarding and I came across this issue.

**Comment by matthias-dunkel** [comment]
Try this:
- Delete `node_modules` folder and `package-lock.json` file and run `npm install` (maybe you need to run it like this `npm install --force --legacy-peer-deps`
OR
- Check if crypto is in the package.json file. If not add `"crypto": "npm:crypto-browserify"` to the dependencies array in the `package.json file`

**Comment by amesk3** [comment]
I've tried the above and still wasn't able to pull it up successfully, unfortunately. Is there no webpack file for us to tweak? I know create-react-app was used so not sure it is available to customize.

**Comment by nmcharlton** [comment]
@amesk3 What versions of npm and node are you using?
We've had this issue reported before, but thought we'd addressed it by adding the following dependency to `package.json`:
```
    "crypto": "npm:crypto-browserify",
```

Can you try adding a browser section to `package.json`:
```
"browser": {
    "crypto": false
}
```

**Comment by amesk3** [comment]
@nmcharlton npm is 6.14.8 and node is v16.14.2 on my machine.

I also tried putting in the browser section as well, no dice :(

**Comment by nmcharlton** [comment]
@amesk3 Those look like incompatible versions to me. Node v16.14.2 should use at least npm 8.5.0.
It's best to use [nvm](https://github.com/nvm-sh/nvm) to manage node versions (if you're not already). Running `nvm use 16.14.2` should switch your npm version to something compatible.

**Comment by amesk3** [comment]
That worked for me! Thank you!
