### ISSUE TITLE
Stakeholders: Empty default organization icon on card

### ISSUE THREAD

**Issue by Vlad-Pischaeff** [Greenstand/treetracker-admin-client#809]
![image](https://user-images.githubusercontent.com/48124219/187188264-ef40d7fa-aee6-45eb-86eb-4b5655bf5a27.png)

**Comment by muhon9** [comment]
<img width="737" alt="Screenshot 2022-08-30 at 4 02 48 AM" src="https://user-images.githubusercontent.com/79197160/187307062-10112ca3-0e20-4646-b63e-a1591dbce1e8.png">


Do we need to show the default greenstand iconlogo if there is no data.logo_url available? @nmcharlton

**Comment by nmcharlton** [comment]
I think a generic placeholder logo would be best. This could a greyscale Greenstand logo.

**Comment by marwan-osama** [comment]
I would like to work on this issue.
