### ISSUE TITLE
Capture Details: Previous capture appears while new selection loads

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#816]
## Steps to reproduce
1. Open capture details for a capture from the Verify or Captures tool
2. Wait for the image to load and close the dialog
3. Open the dialog for another capture
4. Many of the first capture's details (including the image) appear while the new capture loads

https://user-images.githubusercontent.com/5558838/188282201-09e0613c-c38e-471d-98c4-be0548e5a81e.mov

## Desired behaviour
While loading, unknown values show loading indicators (spinner or skeleton) rather than the previous capture

**Comment by marwan-osama** [comment]
I would like to fix this issue.

**Comment by mayankbucha** [comment]
@nmcharlton I would like to work on this.

**Comment by nmcharlton** [comment]
Thanks @mayankbucha

**Comment by marinakosova** [comment]
I created a pull request for the issue. This is my first contribution so please let me know how can I improve it.
