### ISSUE TITLE
Growers: Include all grower images in Edit Grower dialog

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#834]
In the _Edit Grower_ dialog, we currently allow the user to select an image for the grower from their registration images only.
We should also make images from tracking sessions available.

With the legacy API, we need to query captures (trees) where `planterId` matches the selected planter, and get back all of the `planterPhotoUrl` values (note that there will be several duplicate URLs that need to be filtered).

With the new microservices, these images come from the `sessions` endpoint on the Field Data API as `check_in_photo_url`.
![Screenshot 2022-09-19 at 18 50 00](https://user-images.githubusercontent.com/5558838/191081380-8a39ed37-61c5-4dee-a4e3-aa557d947849.png)

**Comment by marinakosova** [comment]
@nmcharlton does master use microservices or legacy API?

**Comment by nmcharlton** [comment]
Sorry @marinakosova, I've messed up here. We're already returning all of these images from the `/planter/:id/selfies` endpoint. I incorrectly thought that these images were registration images, but they're actually from the captures.
That explains why you're getting the same images.

I'll close this issue and suggest we address the problem of selecting a good grower image another way.

**Comment by marinakosova** [comment]
@nmcharlton it make sense. Thank you for clarification.
