### ISSUE TITLE
Capture Matching tool crashes with "Invalid time value"

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#836]
![Screenshot 2022-09-19 at 20 57 43](https://user-images.githubusercontent.com/5558838/191105659-dc51376a-b772-4096-9df0-f6480776a873.png)

**Comment by Vlad-Pischaeff** [comment]
It was my mess

**Comment by nmcharlton** [comment]
> It was my mess

No worries. Thanks for fixing it so quickly!
