### ISSUE TITLE
Grower Detail: Previous capture appears while new selection loads

### ISSUE THREAD

**Issue by marinakosova** [Greenstand/treetracker-admin-client#842]
## Steps to reproduce
1. Open Growers from menu
2. Open the dialog for any uploaded image
3. Wait for the image to load and close the Grower Detail dialog
4. Open the dialog for another capture.
5.  The image from the previous choice appears shortly while the new capture loads

https://user-images.githubusercontent.com/50210952/191373683-d16db9f3-d9c0-44eb-bd65-a95a6f571109.mov

## Desired behaviour
While loading,  show spinner rather than the previous capture

**Comment by marinakosova** [comment]
I would like to work with this issue because recently I fixed similar bug in Capture Detail.

**Comment by nmcharlton** [comment]
Thanks @marinakosova!
