### ISSUE TITLE
Verify - do we need to update the logic of the component?

### ISSUE THREAD

**Issue by Vlad-Pischaeff** [Greenstand/treetracker-admin-client#843]
Component has this code

![image](https://user-images.githubusercontent.com/48124219/191900427-99b143a0-e03e-44b8-938e-75d4ab85ba92.png)

Rerender of the whole component occur every time the browser window is resized
I think it’s unnecessary...

**Comment by Vlad-Pischaeff** [comment]
I try to solve this problem...

**Comment by nmcharlton** [comment]
@Vlad-Pischaeff We recalculate the gallery distribution on resize, but it may be cleaner to do this with CSS.
