### ISSUE TITLE
Edit Growers: Allow user to specify Grower Image URL

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#845]
In the Edit Grower dialog, users can select the best image of a grower from a gallery populated from Treetracker app selfies.
Users should be able to specify an image URL so they can use their own hosted images instead.

Note: The design and implementation should be coherent with #192 (image upload).
Once both of these issues are implemented, users will be able to:
1. Select an existing image
2. Upload a new image
3. Use an externally-hosted image via a URL
![Screenshot 2022-09-19 at 18 50 00](https://user-images.githubusercontent.com/5558838/192095119-34faedd1-bfc7-4c50-a474-289bfac6efbe.png)

**Comment by gustarpd** [comment]
I would like to work on this issue.

**Comment by cvirgili438** [comment]
I would like to work on this
