### ISSUE TITLE
Index.js - react_dom__WEBPACK_IMPORTED_MODULE_2__.createRoot is not a function

### ISSUE THREAD

**Issue by Vlad-Pischaeff** [Greenstand/treetracker-admin-client#847]
1. Fork and clone this repository 
2. ``` npm i --legacy-peer-deps ```
3. ``` npm run start:dev ```
4. Visit [localhost:3001](http://localhost:3001)
5. See blank screen
![image](https://user-images.githubusercontent.com/48124219/192444699-eb3ab942-5d9f-4d40-b372-191cc62bdefb.png)
because the React version is set to 16

Maybe we should explicitly specify the React version in dependencies

**Comment by nmcharlton** [comment]
@Vlad-Pischaeff Thanks for raising this. I think that's a good idea.
