### ISSUE TITLE
Regions: Display complete Region or Collection info in a drawer

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#849]
When a user clicks a row in the Regions or Collections table, they should see the full details of the region in a drawer (see Verify, Captures, Growers, Earnings for inspiration).
![Screenshot 2022-09-28 at 21 23 16](https://user-images.githubusercontent.com/5558838/192881549-a9c31b8a-810f-4c02-8de3-68d7ee7a4270.png)
## Regions
* The region shape on a basic map
* Name
* Owner
* Collection (link to collection details)
* Properties
* Show on Org Map value
* Statistics Calculated value
* Download Shapefile button
* Edit button
* Delete button
## Collections
* All regions on a basic map
* Name
* Owner
* List of regions (each a link to region details)
* Edit button
* Delete button

**Comment by marinakosova** [comment]
@nmcharlton I would like to work on this.

**Comment by marinakosova** [comment]
@nmcharlton I started working on this issue. I noticed that Admin Panel has several tables which made differently. For example, Payments and Earnings tables use CustomTableItemDetails component which is convenient. The Regions table was created from scratch (without use of CustomTableItemDetails with its styles and layout). It is not match work to add styles for a new drawer and even a markup. It is just for your Information.

My progress:
![Screen Shot 2022-10-04 at 4 09 02 PM](https://user-images.githubusercontent.com/50210952/193949465-3ea707f6-abf0-4183-8084-fe6df3707c01.png)

**Comment by marinakosova** [comment]
Hi @nmcharlton. I have questions.
1. In the Regions Drawer what do you mean by "Collection (link to collection details)". I don't know what is the collection details (and region details as well). 
2. Is it ok to display all properties for the Regions Drawer since it is enough space to do this?
3. As I understand in the Regions Drawer I should display "The region shape on a basic map" as a SVG image. I think I need some package like "react-polygon" (https://www.npmjs.com/package/react-polygon). Because from API I got a response with bunch of coordinates. What do you think about it?

**Comment by nmcharlton** [comment]
Hi @marinakosova. Apologies for the slow response.
As discussed on Tuesday:
1. It should be possible to switch between the Region Details drawer and the Collection Details drawer (as shown in your screenshots) by clicking the collection name in the Region Details drawer and any child region name in the Collection Details drawer.
2. Yes. A better component might be the drawer used for Grower Details, which allows the user to scroll. This puts the edit button towards the top of the drawer, beneath the image. Alternatively, you could enable vertical scrolling on the drawer you're using now.
3. I'd suggest using [react-leaflet](https://react-leaflet.js.org/), which has a [GeoJSON API](https://react-leaflet.js.org/docs/api-components/#geojson).
4. Each collection contains a set of regions. When you show Collection details, it should plot all of the GeoJSON features on a map ([react-leaflet](https://react-leaflet.js.org/) again).

I would like to have more consistency with the table styling across the Admin Panel, but this isn't a high priority. If it make it easier to combine the drawer with the table, feel free to refactor the table.

**Comment by marinakosova** [comment]
@nmcharlton I created a pull request with working drawer but without Geo JSON data. I don't want to hold this feature so that user can already use it. 
Is it ok to continue to work with this issue or maybe it is a good idea to create a new one. I never worked with react-leaflet before.

**Comment by marinakosova** [comment]
It looks like my request failed...
