### ISSUE TITLE
Regions: Remove download button from Collections

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#850]
The download button against Collection records does not work and should be removed.
![Screenshot 2022-09-28 at 21 35 03](https://user-images.githubusercontent.com/5558838/192883507-b9fa2990-2a6b-4ab5-a52b-1ff1b3c5bf1b.png)

**Comment by dharmiknotop** [comment]
hey, @nmcharlton I am interested in solving this issue, can you assign this issue to me?

**Comment by dharmiknotop** [comment]
hey, @nmcharlton I had a couple of doubts, how can I login into the website like will you give me the password and id ? and there are multiple backend api repo's so would it be suffice to only install the regoins-api repo?
