### ISSUE TITLE
Capture tool. Download not producing a valid csv file when selecting individual columns 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#851]
See screenshot. The scv file only contains -- Ôªø -- when opened in Excel
![Screenshot 2022-09-29 at 10 12 14](https://user-images.githubusercontent.com/3283800/192964793-e1f1da1a-e390-43ef-98af-af9c14c8761e.png)

**Comment by marinakosova** [comment]
@sebastiangaertner I got the same result like "Ôªø" when I first time downloaded the csv file. After that all other attempts were successful. Weird thing.

**Comment by Vlad-Pischaeff** [comment]
Can I try to fix it?
