### ISSUE TITLE
Verify: Can't select a capture

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#858]
_Version: 1.108.0_

## Steps to Reproduce
1. Open Verify tool
2. Click on a capture
3. Nothing happens

## Expected Behaviour
Capture appears selected: checkbox checked, green background behind card.

**Comment by Vlad-Pischaeff** [comment]
there are two places in **Verify.js**

![image](https://user-images.githubusercontent.com/48124219/193443545-1d92bea7-37f2-41df-8b73-4ac2197d9848.png)

and

![image](https://user-images.githubusercontent.com/48124219/193443576-ad536f0a-a2ba-4590-a38b-b9b6981820e3.png)

where we need to replace **capture.reference_id** to **capture.id**
