### ISSUE TITLE
Verify: Grower info not available

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#859]
_Version: 1.108.0_

## Steps to Reproduce
1. Open Verify tool
2. Click the person icon on a capture card
3. Grower dialog loads with no grower
<img width="1552" alt="Screenshot 2022-10-01 at 17 15 55" src="https://user-images.githubusercontent.com/5558838/193418559-4c90390f-ada3-45e7-adbd-9003dde246fa.png">

## Expected Behaviour
Grower info is shown correctly

**Comment by Vlad-Pischaeff** [comment]
In the previous version we had a field **capture.planterId**, now it is not. Maybe this is the problem

**Comment by Vlad-Pischaeff** [comment]
capture object in Verify.js
> {
>   "id": "d8e9f51c-a72f-47a6-b229-48d011dcc167",
>   "reference_id": "957036",
>   "image_url": "https://treetracker-dev-images.s3.eu-central-1.amazonaws.com/2022.03.29.01.34.36_0.0_0.0_244b5c50-beca-4090-950c-c4e33e169945_IMG_20220329_013400_5793867225582087046.jpg",
>   "lat": "0",
>   "lon": "0",
>   "gps_accuracy": "0",
>   "note": "My Legacy Note",
>   "abs_step_count": 0,
>   "delta_step_count": 0,
>   "rotation_matrix": [],
>   "session_id": "0853ca65-fceb-598c-afc6-bf261380dcfe",
>   "rejection_reason": null,
>   "device_identifier": "48b123d175ceeb4c",
>   "device_configuration_id": "9c451d5e-43e7-5a12-9071-cf3bb78849ce",
>   "grower_account_id": "303917fd-a07d-4f75-80b2-3aad2d32ce36",
>   "wallet": "@TestUser1",
>   "user_photo_url": "https://treetracker-dev-images.s3.eu-central-1.amazonaws.com/2022.03.17.22.48.41_40.712775_-74.00597166666667_aa906165-4f6b-4788-b05a-43a41678e198_IMG_20220317_224832_2894493394749721174.jpg",
>   "extra_attributes": {},
>   "status": "unprocessed",
>   "created_at": "2022-04-04T01:50:04.443Z",
>   "updated_at": "2022-04-04T01:50:04.443Z",
>   "captured_at": "2022-03-29T05:33:59.000Z",
>   "organization_id": null
> }

grower object in GrowerDetail.js

> {
>   "id": 5597,
>   "firstName": "",
>   "lastName": "oaks",
>   "email": null,
>   "organization": null,
>   "phone": "92548323315",
>   "imageUrl": "https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2020.07.21.18.38.41_37.8449304_-122.25714411_348e08db-8fc5-4b67-bb24-eecf294c0dc7_IMG_20200721_183825_8005989450661286921.jpg",
>   "personId": null,
>   "organizationId": null,
>   "imageRotation": null
> }

there is no field match...

**Comment by nmcharlton** [comment]
You're right. `planterId` doesn't exist in the new microservices.
Instead we uniquely identify and query growers using `capture.grower_account_id` which maps to `grower.id`.
GrowerDetails.js should query the new [treetracker-query-api](https://github.com/Greenstand/treetracker-query-api/blob/main/docs/api/spec/query-api.yaml). @gwynndp has [already done some of this work](https://github.com/Greenstand/treetracker-admin-client/pull/806/files#diff-4a0a8a9469071f365c9c4ba21c0756cd6ff0221d7194e489fc6f3859ce967445) on the `change-to-microservices` branch; the change just needs merging into `master`.

**Comment by nmcharlton** [comment]
@gwynndp
