### ISSUE TITLE
Dash Stats: Total Trees count is incorrect for organization users

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#86]
Log in to the Admin Panel as an organization user (e.g. one with the _Freetown Manager_ role).
_Untagged Trees_ plus _Verified Trees_ should equal _Total Trees_.

Instead, _Total Trees_ is reporting the same count for normal and organization users:
![Screenshot 2021-05-10 at 19 43 05](https://user-images.githubusercontent.com/5558838/117708618-f14e9780-b1c7-11eb-9117-e35156362917.png)

**Comment by tranquanghuy0801** [comment]
HI @nmcharlton , can I have a look at this issue?

**Comment by nmcharlton** [comment]
This issue is related to #28.
