### ISSUE TITLE
Verify: Grower map link on capture card uses incorrect URL

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#861]
_Version: 1.108.0_

## Steps to Reproduce
1. Open Verify tool
2. Click the map icon at the bottom of a capture card
3. Web map opens but does not show grower's captures (UUID in URL)

## Expected Behaviour
Web map opens and shows grower's captures

**Comment by nmcharlton** [comment]
@dadiorchen Can we specify the wallet name in the webmap URL?

**Comment by nmcharlton** [comment]
@gwynndp

**Comment by pramodjsam** [comment]
@nmcharlton , I had checked the URL and growerId, and both seems to be same.

![image](https://user-images.githubusercontent.com/33721221/210184389-dbc03f1d-40b1-47a6-be65-59f32d37f2eb.png)

Am i referring to the same ID as mentioned above?

**Comment by nmcharlton** [comment]
@pramodjsam The web map expects the grower `reference_id` in the URL rather than the `id`, e.g., https://beta-map.treetracker.org/planters/4791.

**Comment by pramodjsam** [comment]
@nmcharlton , just confirming, i had replaced the "id" with the "reference_id", 

![image](https://user-images.githubusercontent.com/33721221/210186931-845659f1-2b1b-47f6-8940-66e74ba79948.png)

**Comment by gwynndp** [comment]
Yes, that is correct.  The map links use the reference_ids from the growers.

**Comment by nmcharlton** [comment]
@pramodjsam That value looks very high for a grower reference ID - are you sure it's not the _Capture_ reference ID?

**Comment by pramodjsam** [comment]
@nmcharlton This is the value that i took for reference_id

![image](https://user-images.githubusercontent.com/33721221/210269937-34883559-a42d-4e3a-92d6-865cc249fcd3.png)

**Comment by nmcharlton** [comment]
@pramodjsam Yep, that's the _capture_ reference ID, not the _grower_ reference ID. We currently don't have the grower in the capture object we get from the API, so we need to do one of three things:
1. Have the query API include the grower reference ID in the capture object
2. Look up the grower reference ID dynamically from the Admin Panel for each capture - we could be clever and only do this at the point the user hovers over the capture to minimise API calls
3. Update the web map to work with `grower_account_id` as well as reference ID

@Kpoke @dadiorchen Any suggestions?

**Comment by nmcharlton** [comment]
> @pramodjsam Yep, that's the _capture_ reference ID, not the _grower_ reference ID. We currently don't have the grower in the capture object we get from the API, so we need to do one of three things:
> 
> 1. Have the query API include the grower reference ID in the capture object
> 2. Look up the grower reference ID dynamically from the Admin Panel for each capture - we could be clever and only do this at the point the user hovers over the capture to minimise API calls
> 3. Update the web map to work with `grower_account_id` as well as reference ID
> 
> @Kpoke @dadiorchen Any suggestions?

@Kpoke @dadiorchen Did we settle on a decision for this?

**Comment by Kpoke** [comment]
I am leaning towards number 1, that'll be straightforward and easy to update

**Comment by Kpoke** [comment]
Implemented number 1 for this, you can find the grower_reference_id as part of the Capture payload

**Comment by cvirgili438** [comment]
Can assign it to me ? 
I will try to do this.
