### ISSUE TITLE
Grower Tool - Incorrect different types of captures count

### ISSUE THREAD

**Issue by tranquanghuy0801** [Greenstand/treetracker-admin-client#868]
In grower tool, the Grower Detail dialog of each grower shows similar number of captures count for each status (Approved, Awaiting, Rejected), which I believe this is incorrect. See the attached image.

![image](https://user-images.githubusercontent.com/29462498/193455175-66cde9ad-527f-42c3-9a4a-3099a5f58ecb.png)

**Comment by Vlad-Pischaeff** [comment]
It seems to me that all recent bugs due to the latest **treeTrackerApi** update

**Comment by nmcharlton** [comment]
@gwynndp

**Comment by pramodjsam** [comment]
@nmcharlton , there seems to be a problem in growers tool in the code, where the we are using the wrong property of the object and thus the "awaiting" status count will be always zero.

The property we are receiving are 
![image](https://user-images.githubusercontent.com/33721221/210182312-dd3cb2dc-3510-4279-a145-3f1a6865ccb6.png)

But in the code, we are using 
![image](https://user-images.githubusercontent.com/33721221/210182317-66c3d87b-d7c7-4bdf-b88d-c8fca722f73b.png)

So, the solution is to use the appropriate object property to the awaiting status ie "unprocessed". Correct me if I am wrong.
