### ISSUE TITLE
Grower tool. Filter organization = "not set" is not working

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#869]
When selecting the filter option organization = "not set" it does not show the the planters without an organization. This is obvisouly a very legacy logic so the question is if it is worth fixing now since in the future this will be coming from the contract right?
![Screenshot 2022-10-03 at 07 35 22](https://user-images.githubusercontent.com/3283800/193502583-29657231-2f86-40ae-b7bd-87fde158ad48.png)

**Comment by nmcharlton** [comment]
This appears to be a bug in the client query to the legacy API.
It may be worth fixing this on https://github.com/Greenstand/treetracker-admin-client/tree/hotfix/v1.107.

**Comment by sebastiangaertner** [comment]
ok. great. Did someone pick this up yet?

**Comment by nmcharlton** [comment]
> ok. great. Did someone pick this up yet?

Not yet.

**Comment by nmcharlton** [comment]
This is still not working following migration of the tool to the query-api `grower-accounts` endpoint.

**Comment by Vlad-Pischaeff** [comment]
It seems to me that if the backend can accept an empty value and process it, then we can get a list where **organization_id = null** (users with organization = "not set")

I tried to query with an empty value:
**https://dev-k8s.treetracker.org/query/grower-accounts?organization_id=%00&limit=24&offset=0**

But I got it
{"code":422,"message":"\"organization_id\" must be a valid GUID"}

**Comment by nmcharlton** [comment]
@Kpoke Is a `null` query supported by the API?

**Comment by Kpoke** [comment]
Don't think it is yet but the API could be extended to support that logic

**Comment by pramodjsam** [comment]
@nmcharlton , as mentioned above, we receive an error when the organization is kept as null in the query string.
{
"code": 422,
"message": "\"organization_id\" must be a valid GUID"
}

I had found a fix, where we can filter the organization values from the client side itself when the organization_id value is null. Tested the same in the dev environment and I am able to successfully receive 20 organization which is having a value of null as organization_id. 

![image](https://user-images.githubusercontent.com/33721221/208797540-bd17066c-400f-42b6-a0f6-b18071259550.png)

**Comment by Vlad-Pischaeff** [comment]
I think maybe I’m wrong, the point is that the filtering is now on the server and there it should stay and smear the filtering on the client and server wrong. Either we leave the task to the server or transfer it to the client. You have to choose one.

**Comment by pramodjsam** [comment]
@Vlad-Pischaeff Ideally in this case, filtering should be done from the server side. But due to some issue in the API, we are not able to fetch the data when the organization id is null. So, as a hot fix, we could filter it from the client side, and when the API is fixed, we could revert it back.

**Comment by Vlad-Pischaeff** [comment]
There is nothing more permanent than a temporary solution...
tested...

**Comment by nmcharlton** [comment]
@pramodjsam There's an PR in progress on the API: Greenstand/treetracker-query-api#268
Let's wait for that to be resolved.

**Comment by OlhaD** [comment]
@nmcharlton The PR you mentioned was merged and the filter seems to work. Do you think this ticket should be closed?

**Comment by nmcharlton** [comment]
@OlhaD You're right, we can close this now.
