### ISSUE TITLE
Capture tool on download no URL in csv export file

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#870]
![Screenshot 2022-10-03 at 20 14 15](https://user-images.githubusercontent.com/3283800/193638667-c72eaa3b-e2b8-475e-99ca-7ad2e38d6439.png)

**Comment by thomascouto** [comment]
Hello, the csv file shows correctly in my desktop

![image](https://user-images.githubusercontent.com/16022815/193936107-2b04dc85-dc56-4e71-ba96-0dc402f6ec26.png)

**Comment by nmcharlton** [comment]
@thomascouto It looks like @Vlad-Pischaeff fixed this under #856. Let's apply the fix to the `hotfix/v1.107` branch and get a new release out to prod.

**Comment by thomascouto** [comment]
Thanks, gonna find another issue to solve :)

**Comment by nmcharlton** [comment]
@Vlad-Pischaeff Could you apply your fix to the hotfix branch?

**Comment by Vlad-Pischaeff** [comment]
Finished. 
Branch hotfix/v1.107

**Comment by nmcharlton** [comment]
Fixed in hotfix branch; already fixed in `master`
