### ISSUE TITLE
Add wallet to grower detail view

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#872]

**Comment by pramodjsam** [comment]
@gwynndp Added teh wallet to the grower detail view.

Before enhancement:
![image](https://user-images.githubusercontent.com/33721221/210183997-3c720f8f-5fbc-46fe-a509-41ff2a7a6a47.png)


After enhancement:
![image](https://user-images.githubusercontent.com/33721221/210184012-9bd8ec98-4779-4fb8-81ec-da71aa0dfdf8.png)
