### ISSUE TITLE
Add a spinner while the image loads up in verify page

### ISSUE THREAD

**Issue by dharmiknotop** [Greenstand/treetracker-admin-client#879]
it shows a blank white space for some seconds while the image loads up, so add a spinner while the image is loading up.

### **Steps to reproduce**
1. Go to verify tab. 
3. the Image loads up after some Delay in that while it shows a white blank space.

### **Expected Behaviour**
 show a spinner while the image load's up

![image](https://user-images.githubusercontent.com/73011112/193978990-392f0929-baa8-4165-b031-1bd4c9cee2af.png)

I am solving this

**Comment by nmcharlton** [comment]
@dharmiknotop I wonder if  `Skeleton` might look better here.

**Comment by dharmiknotop** [comment]
umm, yea same thought came after I saw too many spinner's on my screen for a sec : | so, your call should I Implement or not but like can we increase the speed in which the image loads up? cause they are not going good ux.

**Comment by nmcharlton** [comment]
I've asked the cloud team to add a CDN for the image resizing API so we don't have to dynamically regenerate the images each time (as we do now). That will speed up loading significantly.
