### ISSUE TITLE
Display organization name alongside organization ID and distinguish from field data

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#88]
A planter can have two values for their organization:

1. The name they type in when prompted by the Treetracker app (`organization` field in the `planter` record)
2. The organization assigned to them (currently by an Admin Panel user, but soon as part of the app sign up process, `organizationId` field in the `planter` record)

The current workflow to assign the correct org [2], and link the planter to that org in the db so that they appear for the appropriate org Admin Panel users, is a manual process of searching for entered org names [1] that closely match the one we want.

There are two problems with the way this information is currently displayed in the Admin Panel that need to be addressed:

- It's not clear to the user that these are different things – _Organization_ should be labelled as originating from the planter and Assigned Organization labelled as such
- We typically display only the ID of the assigned organization – we should display both the ID and the name, e.g. __Freetown [11]__

~~An alternative option would be to remove the display of IDs from the client altogether and just display names.~~

![Screenshot 2021-05-16 at 16 32 22](https://user-images.githubusercontent.com/5558838/118403448-470ebe00-b666-11eb-8fac-f5611957623d.png)

These changes will need to be applied everywhere we reference the organization:

- Planters
- Planter Detail
- Edit Planter
- Verify Filter

**Comment by sebastiangaertner** [comment]
It's good to keep the ID as well 
--
Sent from myMail for Android Sunday, 16 May 2021, 11:20pm +03:00 from Nick Charlton  ***@***.*** :

**Comment by sebastiangaertner** [comment]
Just to double check currently its the entity table and only if type is a capital O they should appear on the drop down in the planter edit section or?

**Comment by nmcharlton** [comment]
> Just to double check currently its the entity table and only if type is a capital O they should appear on the drop down in the planter edit section or?

@sebastiangaertner That is the intended behaviour.
The current version on admin.treetracker.org erroneously looks for _lowercase_ o, but @gwynndp is in the process of fixing it as part of #87.

**Comment by VLuisa** [comment]
@nmcharlton I could take a look at this one!

**Comment by VLuisa** [comment]
@nmcharlton  Just double checking I'm understanding this correctly... So we want to update the organization labels to be two fields:
1. 'Assigned Organization': `Organization Name` + `[Organization Id]` 
2. 'Organization': `Organization Name`

Is the `Organization Name` the same in both or is there an `Assigned Organization Name` field in the data that just isn't being displayed currently?

**Comment by nmcharlton** [comment]
@VLuisa That's correct.
1. The assigned organization name comes from a lookup of the organization ID using the `/organizations` endpoint or `organizations` model.
2. We need to make it clear that this one is the _planter-entered_ organization - @sebastiangaertner might have be able to suggest what this label should say.

**Comment by nmcharlton** [comment]
Proposed UI design for this:
![image](https://user-images.githubusercontent.com/5558838/127399038-714d9396-1948-4c32-8671-1356ceee04f3.png)

**Comment by VLuisa** [comment]
@nmcharlton Thanks for sharing the designs, it helped clarify a lot! I got the Planter Detail working and will update it in the other relevant places next

![image](https://user-images.githubusercontent.com/10137547/127746095-f7a04bcf-b589-4206-b9b1-c23165f1c718.png)

**Comment by nmcharlton** [comment]
Great work @VLuisa!
I'm now wondering whether we actually need these org web map links.
We don't yet pull the map name from the database, so would need some extra work on the API to support this functionality anyway.

Seb has proposed just displaying the ID in brackets after the org name, but I'm not convinced that gives sufficient visual distinction. What do you think?

![image](https://user-images.githubusercontent.com/5558838/127751292-e5d28887-f867-4d24-baf1-5d3de63b8c43.png)

**Comment by VLuisa** [comment]
@nmcharlton Hmm that's a good point - agreed that it's not particularly visually distinct, however the braces could be a good solution if we want to be able to display that same UI as part of the planter list tile since it pretty condensed. Another option could be "Bob for Trees — 44" or "44: Bob for Trees".

**Comment by nmcharlton** [comment]
@VLuisa I think any of those would work well. Go with what you think looks best.

**Comment by tranquanghuy0801** [comment]
@nmcharlton can I take on this issue?

**Comment by Jhngrntn** [comment]
Commenting to show username to assign the issue

**Comment by nmcharlton** [comment]
Sorry @tranquanghuy0801, I asked @Jhngrntn to look at this one.

**Comment by tranquanghuy0801** [comment]
@nmcharlton Just alright, thanks for letting me know.
