### ISSUE TITLE
Grower: new filter by amount of captures uploaded.

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#888]
It would be great to have a simple filter
0
1-25
more than 25

**Comment by nmcharlton** [comment]
This will likely need a corresponding change in the API to query by number of captures.

**Comment by nmcharlton** [comment]
This is ready for someone to make a start on and to hook up to the API as soon as Greenstand/treetracker-query-api#275 is ready.

**Comment by OlhaD** [comment]
@nmcharlton I would like to start working on it.
