### ISSUE TITLE
Master branch does not pass tests

### ISSUE THREAD

**Issue by Vlad-Pischaeff** [Greenstand/treetracker-admin-client#894]
How to reproduce:

- git clone https://github.com/Greenstand/treetracker-admin-client.git
- npm install
- npm run test

result

![image](https://user-images.githubusercontent.com/48124219/195753161-4cbdf982-298e-4919-a3b2-728661551205.png)

**Comment by SuspenseFallback** [comment]
I can't seem to be able to reproduce this.
<img width="519" alt="Screenshot 2022-10-31 at 9 04 27 PM" src="https://user-images.githubusercontent.com/86506971/199014543-9280a41c-4ba5-478a-a410-b6d0518a4e01.png">

**Comment by nmcharlton** [comment]
I am also seeing all tests pass. Closing for now.
