### ISSUE TITLE
Verify/Captures: Filter by session

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#896]
## New Feature
A filter in the Verify and Captures tools that allows the user to see all captures from a specific tracking _session_.

![Screenshot 2022-10-16 at 16 45 04](https://user-images.githubusercontent.com/5558838/196044693-8464fc38-3f47-4daa-b891-d60c58bba0e3.png)

## Desired Behaviour
1. In the filter, users see a list of sessions labeled with start date/time (`session.created_at`) and wallet name (`session.wallet`). E.g., `2022-10-16 16:54 | treetracker@sustainably.run`.
2. Dates are displayed using the locale format, as with other dates in the Admin Panel.
3. Sessions are sorted by `created_at` with the most recent at the top.
4. There will be thousands of sessions, so only the first 50 are displayed initially.
5. Users can search the list by wallet name or date (similar to the _Tag_ filter).
6. We only show the sessions the user has permission to view, according to their organization (using `session.organization_id`). The implementation for this should follow the pattern for other filters (e.g., _Organization_), which may require some coordination with the Keycloak implementation (#261, [Keycloak project](https://github.com/orgs/Greenstand/projects/47)).

## Sessions
The list of sessions can be queried from query API (`$REACT_APP_FIELD_DATA_API_ROOT/session/`, see [field-data spec](https://github.com/Greenstand/treetracker-field-data/blob/main/docs/api/spec/api.json)).

## Dependencies
Depends on Greenstand/treetracker-query-api#244

**Comment by maxt0214** [comment]
@nmcharlton 
I have added a component for session list, but I am having  cors issue with the old api `$REACT_APP_FIELD_DATA_API_ROOT/session/` 

The error is here:

<img width="1920" alt="Sessions" src="https://user-images.githubusercontent.com/49177628/212801616-c4e23091-e446-42a0-87ff-6a4100aab462.png">

I followed getOrganizations to getSessions:

<img width="1017" alt="sessionAPI" src="https://user-images.githubusercontent.com/49177628/212801723-34e60884-3038-426a-a514-6471da3b7ae9.png">

Is the CORS issue on the server side? If so, I could try to first work on https://github.com/Greenstand/treetracker-query-api/issues/244

**Comment by nmcharlton** [comment]
CORS issue captured in Greenstand/treetracker-field-data#86

**Comment by nmcharlton** [comment]
@maxt0214 Please go ahead and start on https://github.com/Greenstand/treetracker-query-api/issues/244 if you haven't already. Add a comment to the issue so it can be assigned to you and shout if you need any help.
