### ISSUE TITLE
Capture Matching: Don't truncate capture reference ID

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#897]
![Screenshot 2022-10-16 at 17 49 29](https://user-images.githubusercontent.com/5558838/196047780-901b6430-ca05-4cf7-82eb-682f80f1980c.png)

We're unnecessarily truncating the ID we display for captures on the left side of the Capture Matching tool.
This is a hangover from when we displayed the long UUID instead of the shorter reference ID.

**Comment by ujwalkumar1995** [comment]
Hey @nmcharlton 
I would like to work on this.  Could you please assign to me?

**Comment by ujwalkumar1995** [comment]
Hey @nmcharlton 
I have created the PR to fix this. Could you please review?
