### ISSUE TITLE
Link to map goes to Treetracker.org and fails

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#90]
See attached. 
![TicketSeb](https://user-images.githubusercontent.com/3283800/119018510-d12b8f00-b9a4-11eb-857d-8592882f9072.png)
Strangely the one link works and the other does not

**Comment by nmcharlton** [comment]
@sebastiangaertner Are you getting a certificate error?
There appears to be a problem with the certificate on https://treetracker.org meaning it doesn't correctly redirect to https://map.treetracker.org.

I'll update the build script to use the new direct web map url.
