### ISSUE TITLE
Dismiss filter drawer on background click or ESC keypress

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#914]
When the Capture Matching filter drawer is open, the user should be able to dismiss it by either clicking anywhere outside the drawer (background) or by pressing ESC. Currently, they have to press the `X` button, which is fiddly.
<img width="1552" alt="Screenshot 2022-11-03 at 20 22 59" src="https://user-images.githubusercontent.com/5558838/199826676-d0d739f9-b754-45ff-9c87-0e931c5ed948.png">

**Comment by nmcharlton** [comment]
This also applies to the filters in the Earnings and Payments tools, which should also grey out the background when the drawer is open.
<img width="1552" alt="Screenshot 2022-11-03 at 20 27 27" src="https://user-images.githubusercontent.com/5558838/199827203-1563c3de-ab24-4e38-be9e-7a2be7de89f3.png">

**Comment by thomascouto** [comment]
Hello, I've completed this pr already. What branch should I push it ?
