### ISSUE TITLE
Reporting cards: new reporting card for number of Trees

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#917]
A **"Tress"** reporting card with exactly like the "**Captures**" card needs to be added to the home screen.

**Comment by sebastiangaertner** [comment]
![Screenshot 2022-11-04 at 11 57 45](https://user-images.githubusercontent.com/3283800/199933078-08bd3316-be0a-472f-9986-243a13e485e1.png)
![Screenshot 2022-11-04 at 11 57 34](https://user-images.githubusercontent.com/3283800/199933089-ef692bc9-5d68-45c0-8d84-451d5ffaf83c.png)


Both of these

**Comment by SuspenseFallback** [comment]
I don't have too much experience here, so what is `treetracker.tree`?

**Comment by nmcharlton** [comment]
From the perspective of the client, this will likely be a new `trees` item in the response to a `/reporting/capture/statistics` API query (reporting-api):
```
{
  captures: {total: 1123164, captures: [{name: "FCCFED", number: "316601"}, {name: "FCCYAR", number: "238520"},…]},
  catchments: {average: 82508,…},
  gender_details: {total: 918, gender_details: [{name: null, number: "918", percentage: 100}]},
  last_updated_at: "2022-11-05T00:00:10.376Z",
  planters: {total: 918,…},
  species: {total: 32, species: [{name: "Rhizophora mucronata (Red Mangrove)", number: "58994"},…]},
  top_planters: {average: 1258,…},
  trees_per_planters: {average: 1097,…},
  unverified_captures: {total: 31947,…},
}
```

`treetracker.tree` just refers to the DB table that stores the list of trees. In practice, the reporting API aggregates all captures and counts how many different trees appear attached to captures.

**Comment by nmcharlton** [comment]
This depends on Greenstand/treetracker-reporting#56.
The card should appear on the top row of the dashboard as it's one of the most important ones.

**Comment by SuspenseFallback** [comment]
Can I be assigned to this issue?

**Comment by nmcharlton** [comment]
Note: There's little benefit in creating a new card for the legacy dashboard, since all organizations will soon move across to the new dashboard under #654.

**Comment by dadiorchen** [comment]
I think this is still the old problem, in dev, the service randomly fails, for me, there is 30% probability that the request fails.

**Comment by dadiorchen** [comment]
@emmanue any cludes on this?

**Comment by dadiorchen** [comment]
@emmanue I have fixed this problem, there is a extra invalid mapping for reporting, after deleting that one, it's all good.

**Comment by jontatan25** [comment]
I would like to work on this issue!

**Comment by dadiorchen** [comment]
@jontatan25 thank you for taking this, this is one of our major focus, please let me know if you need any support! you can find me on slack with the same name

**Comment by nmcharlton** [comment]
@jontatan25 https://github.com/Greenstand/treetracker-reporting/issues/57 has now been merged.

**Comment by TseChapman** [comment]
@nmcharlton I want to ask if this issue is finished, if not, I would love to take it

**Comment by nmcharlton** [comment]
@TseChapman I think you can go ahead. We haven't seen a PR for this issue yet.

**Comment by TseChapman** [comment]
![image](https://github.com/Greenstand/treetracker-admin-client/assets/49383826/81cd100f-3539-40ae-8763-da26e5477aee)
@nmcharlton Thank you, I was able to get the reporting card for trees on the home page. The bottom right corner of the image above.

I have a question on how do I get to the page shown by sebastiangaertner (image below is a screenshot of the image posted by sebastiangaertner):
![image](https://github.com/Greenstand/treetracker-admin-client/assets/49383826/75435f76-a59d-427c-8c37-9adb3c19df53)
Furthermore, I notice that DashStat related component display differently based on the account's policy/permission in the Home page. Is there specific policy required to display Tree stat?

**Comment by dadiorchen** [comment]
I think the tree stat just apply to freetown account, for freetown, we display different stat if I remember it correctly

**Comment by TseChapman** [comment]
@dadiorchen You are correct. Based on my research into the reporting and query repository, I saw both trees api return a total tree count. I wanna ask if I can follow the same pattern on ReportingCards and DashStat, where ReportingCards uses the reporting api and DashStat using the query api?

**Comment by dadiorchen** [comment]
I'm not sure, @nmcharlton can you give some guide?

**Comment by nmcharlton** [comment]
The legacy DashStat cards are being phased out, so there's no need to make the changes there. Soon, the newer Reporting Cards will be used by all organizations.

**Comment by TseChapman** [comment]
@nmcharlton If that is the case, I don’t need to create the DashStat component for trees right? Just the reporting card.

**Comment by nmcharlton** [comment]
> @nmcharlton If that is the case, I don’t need to create the DashStat component for trees right? Just the reporting card.

Correct.

**Comment by TseChapman** [comment]
@nmcharlton I created a pull request for reviews
