### ISSUE TITLE
Home: Axios Error 503 on reporting/capture/statistics?

### ISSUE THREAD

**Issue by SuspenseFallback** [Greenstand/treetracker-admin-client#920]
On Home.js, this error appears in the console after a few seconds:

<img width="407" alt="Screenshot 2022-11-05 at 10 00 45 AM" src="https://user-images.githubusercontent.com/86506971/200096210-b2ce0514-406f-4ee7-bd8c-0b384e9b4f84.png">

Home.js:62 

```
// the reporting card, update time, the time range
  useEffect(() => {
    async function loadUpdateTime() {
      const res = await axios(
        `${process.env.REACT_APP_REPORTING_API_ROOT}/capture/statistics?`
      );
      const { data } = res;
      setUpdateTime(data.last_updated_at);
    }
    loadUpdateTime();
  }, []);
```

**Comment by nmcharlton** [comment]
This looks like an issue with the deployment. I've asked the cloud team for assistance.

**Comment by dadiorchen** [comment]
Can you check it again, it's back now

**Comment by SuspenseFallback** [comment]
Yeah, the error is still there.

**Comment by dadiorchen** [comment]
@SuspenseFallback please check it again

**Comment by SuspenseFallback** [comment]
It's gone now.
