### ISSUE TITLE
capture: filter does not work

### ISSUE THREAD

**Issue by SuspenseFallback** [Greenstand/treetracker-admin-client#923]
The capture filter doesn't work, although it works in Verify
<img width="1440" alt="Screenshot 2022-11-07 at 8 40 22 PM" src="https://user-images.githubusercontent.com/86506971/200312805-537f8a78-4022-492a-a344-e197a692b738.png">
As seen above, the rejected filter doesn't work.

Edit: Not only the verification filter, but the Grower ID and Capture ID too. The Capture UUID gives an error - #935

**Comment by AlexandreDaltro** [comment]
Here I`ve cloned it today, and only the Capture UUID works. None of the others are working.

![image](https://user-images.githubusercontent.com/105553750/202327143-96c41e0b-392c-4f11-b79f-07150292e8ec.png)

**Comment by nmcharlton** [comment]
Resolved by #963
