### ISSUE TITLE
Insufficient space for Additional tags warning message

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#93]
If you try to enter an invalid character in the _Additional tags_ input on the _Verify_ tool, you'll see a warning beneath the input.
This warning is too close to the elements below, making it hard to read.

![Screenshot 2021-05-24 at 19 44 55](https://user-images.githubusercontent.com/5558838/119393488-eb2ce080-bcc8-11eb-8e53-2972558f1567.png)

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton, can I work on this issue?
