### ISSUE TITLE
The location and country name with capture matching tool is broken

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#930]
As shown in the picture, the location of the capture is empty, and if click the location icon, the map is wrong to show the location of this capture.
<img width="1427" alt="Screen Shot 2022-11-11 at 12 00 19 PM" src="https://user-images.githubusercontent.com/5744708/201260664-3730348d-3fb0-41a3-b21c-33ee3adb09e8.png">

**Comment by janet-yu** [comment]
I'd like to take this issue on!
