### ISSUE TITLE
Captures: AxiosError: Internal Server Error

### ISSUE THREAD

**Issue by SuspenseFallback** [Greenstand/treetracker-admin-client#935]
On the Captures page, an error pops up in the console when submitting a Capture UUID  - 500 (Internal Server Error).

<img width="531" alt="Screenshot 2022-11-14 at 1 39 08 PM" src="https://user-images.githubusercontent.com/86506971/201583746-05b28aaa-93cd-4aab-baca-6969e754e376.png">

**Comment by nmcharlton** [comment]
This is a mid-migration issue: we're querying the legacy API `id` field (integer) with the new UUID (string).
@gwynndp: One to fix as part of the Captures migration.
