### ISSUE TITLE
Add wallet to Capture Detail Dialog

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#938]
Currently the wallet id shows in the Capture Tool Tip but still shows as blank in the Capture Detail Dialog.

**Comment by janet-yu** [comment]
I'd like to work on this!

**Comment by janet-yu** [comment]
Question: Are different fields returned based on the endpoint hit? For instance, the captures returned when hitting `/raw-captures` to fetch all captures, it returns the captures with the `wallet` field. But when hitting `/raw-captures/:capture_id`, the capture returned doesn't have the `wallet` field.

Example capture returned from hitting `/raw-captures` (the captures rendered in the Verify page):
![captureFromVerify](https://user-images.githubusercontent.com/38471377/202355490-3084d8eb-c72e-4540-905e-846c7ad6a4f0.png)

Capture returned from `/raw-captures/:capture_id` (this is what's rendered in the CaptureDetailDialog I believe):
![captureInDialog](https://user-images.githubusercontent.com/38471377/202355505-3310f06e-c2e0-4209-8f9e-750f4e7c7c90.png)
This capture also has some more fields that isn't available in the corresponding capture from the raw captures array above.

**Comment by janet-yu** [comment]
@nmcharlton Just wanted to check in on this issue, is there documentation where I can check what object we expect to be returned by the API?

**Comment by gwynndp** [comment]
@janet-yu Thank you -- good catch!  
The api should return the same data in the object.  This should be an issue for the Field-Data api @Kpoke

**Comment by gwynndp** [comment]
@janet-yu You should be able to pick up work on this again once the api is updated.  Here is the issue you can follow: https://github.com/Greenstand/treetracker-field-data/issues/85

**Comment by janet-yu** [comment]
Sounds good! I'll pick up another ticket in the meantime.

**Comment by nmcharlton** [comment]
The API dependency mentioned has now been completed, so work on this issue can continue.

**Comment by janet-yu** [comment]
Hmm, I'm still finding that the response from `/raw-captures/{capture_id}` still isn't returning the `wallet` field.

Request URL: https://dev-k8s.treetracker.org/query/raw-captures/aa5504e4-20fd-49fb-a2e8-50fba9f9ab59
Request response:
![capture-resp](https://user-images.githubusercontent.com/38471377/216882956-c19bf132-a94a-4e4d-b7e3-01fe23c40e87.png)

**Comment by nmcharlton** [comment]
@Kpoke There's a mismatch in the fields returned by `/query/raw-captures` and `/query/raw-captures/:id`. As @janet-yu mentions, `wallet` is missing from the `/:id` response, but also `user_photo_url`. Can we get those two added?

**Comment by Kpoke** [comment]
Fixed this.

**Comment by pranavkparti** [comment]
This issue seems to be resolved?

The Capture Tooltip:
![image](https://github.com/Greenstand/treetracker-admin-client/assets/15161954/bc27f136-bbd4-49b1-8e88-7d871b684ee8)
The Capture Detail Dialog:
![image](https://github.com/Greenstand/treetracker-admin-client/assets/15161954/82e90fc9-a869-4169-aa28-19f828a1bcec)

I hope this what the issue is referring to.
