### ISSUE TITLE
Taller images breaks the design in capture matching making it impossible to use.

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#941]
See screenshot
![Screenshot 2022-11-15 at 21 06 54](https://user-images.githubusercontent.com/3283800/201993959-ad0359eb-a22f-4beb-9e17-ecbb9a33f7d1.png)

**Comment by nmcharlton** [comment]
All images should be the same hight with variable width.

**Comment by navDhammu** [comment]
Adding a fixed height and variable width causes the capture details to overflow.

<img width="460" alt="Screen Shot 2022-11-16 at 11 38 53 AM" src="https://user-images.githubusercontent.com/73000930/202240286-e970ca74-aba0-49a8-98a4-0a5395c16afd.png">

**Comment by sebastiangaertner** [comment]
@navDhammu Thank you for picking this up! @nmcharlton can this be merged fairly quickly? It currently breaks the testing in beta which we have now started based on live data.

**Comment by dadiorchen** [comment]
It has been solved in the hotfix/107, @nmcharlton what shall we do on this case? Fixed bug on hotfix/107, and sync to master?

**Comment by nmcharlton** [comment]
@dadiorchen Yes. I think a PR against `master` with the hotfix branch deltas would be easiest.

**Comment by nmcharlton** [comment]
Fixed in `hotfix/v1.107` and merged into `master`
