### ISSUE TITLE
A error causes the matching tool to crash

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#942]
Looks like a special date will crash the panel:

![Image](https://user-images.githubusercontent.com/5744708/202111804-d1373d82-71cb-4b5e-a139-cf1df538beaa.png)

![Image](https://user-images.githubusercontent.com/5744708/202111946-3ead7fc3-4fb5-4aba-a2b5-a4017a8bcd04.png)

![Image](https://user-images.githubusercontent.com/5744708/202111986-f8fd3bd2-aaf2-48d1-ba70-355e4bed7230.png)

**Comment by AlexandreDaltro** [comment]
Hello! How could I reproduce this error? 
I tried to use the filter with different values, but couldn`t get the error.

**Comment by dadiorchen** [comment]
Did you join our slack? can you reach me on Slack? If not can you leave your email so I can invite you?
