### ISSUE TITLE
Species: Adding species does no longer work. No error shown

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#959]
In production adding new species is no longer working.

**Comment by nmcharlton** [comment]
@sebastiangaertner Can you retest this? I've deployed the legacy API fix to production.

**Comment by nmcharlton** [comment]
Addressed in Greenstand/treetracker-database#110

**Comment by nmcharlton** [comment]
Addressed in Greenstand/treetracker-database#106
