### ISSUE TITLE
Clicking Planter ID on planter card should not open Planter Detail

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#96]
Clicking a planter card in the _Planters_ page opens the _Planter Detail_ dialog.
Clicking the _ID_ opens the web map for that planter, but also erroneously opens the _Planter Detail_.

The _ID_ clicks should not be passed through to the card.

https://user-images.githubusercontent.com/5558838/119401805-f1748a00-bcd3-11eb-97d7-c1b5d8017317.mov

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton, check my latest PR about this issue. Thanks
