### ISSUE TITLE
Verification no longer working when adding a tag

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#964]
When going through normal verification and using tags it does no longer work. this is in production and has been confirmed by several users. See screenshot of the console. 
![Screenshot 2022-11-29 at 21 44 42](https://user-images.githubusercontent.com/3283800/204618982-de5b6cc8-25ac-4941-83d2-8c27e84289d0.png)

**Comment by nmcharlton** [comment]
Addressed in Greenstand/treetracker-database#110
