### ISSUE TITLE
Increase default number of rows per page in Species table

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#97]
The default page size (rows per page) in the Species tool is unnecessarily low (5).
The page size options should be increased to something more sensible, e.g. 25, 50 and 100.

![Screenshot 2021-05-24 at 21 19 42](https://user-images.githubusercontent.com/5558838/119403141-cd19ad00-bcd5-11eb-9208-7eb57a12962d.png)

**Comment by EdJaPe** [comment]
Hello Everyone,
I will take this issue as my first issue to fix.
