### ISSUE TITLE
Growers: Cards are missing information

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#970]
The grower cards should show basic information about the grower, but are mostly blank in dev.
We should see:
* First name and last name
* Reference ID (not UUID, as is currently shown)
* Organization name
<img width="1552" alt="Screenshot 2022-12-03 at 15 48 15" src="https://user-images.githubusercontent.com/5558838/205449568-0415adc0-b7ac-4f60-bed0-971a3addf28e.png">

**Comment by CODE-Y02** [comment]
Hi @nmcharlton I am new to open source , I have Knowledge of JS , Node and SQL but I am begineer in react , Is this issue will be good for me to start with and can you please guide me a little on how do i get started .

**Comment by vradriano** [comment]
@nmcharlton Is it free? I will take this one

**Comment by nmcharlton** [comment]
@CODE-Y02 As you were first to comment, I'll assign this to you (sorry @vradriano).
You'll need to [sign up as a Greenstand contributor](https://docs.google.com/forms/d/e/1FAIpQLSdyLUffLPZZlHR-qfMwch5HkWcZ3kxM6h-eMK5PfGKLD4t8iA/viewform) to get access to our Slack.

In the meantime, follow the instructions in the project Readme to get set up.

**Comment by vradriano** [comment]
@nmcharlton No sweat! I'm gonna find another to work.

**Comment by David50Z** [comment]
Could I be assigned to this issue?

**Comment by nmcharlton** [comment]
Sorry @David50Z, @CODE-Y02 is already working on this.
