### ISSUE TITLE
Legacy Growers count dash stat not working

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#971]
The Growers dash stat card adds `?active=true` to the query.
This is not valid in the new microservice API world and should be omitted.
<img width="1552" alt="Screenshot 2022-12-03 at 15 56 18" src="https://user-images.githubusercontent.com/5558838/205449895-8f01eb7d-a353-4625-82ef-bae53daf9480.png">

**Comment by CODE-Y02** [comment]
hi @nmcharlton  I just pinged on another thread , Please don't think  I am spamming , 
I have some knowlege about backend and as I can see on screen shot , there a problem in api url where we care calling api ,
message must be message: "active"  not ""active"  

If you can guide me  maybe i can fix this bug
