### ISSUE TITLE
Combine Species: checked species are lost when changing pages

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#98]
The _Combine Species_ feature in the _Species_ tool works by checking the boxes against two or more species and clicking _Combine Species_.

Steps to reproduce problem:

1. Go to _Species_ page
2. Select a species checkbox
3. Click to next page of table
4. Go back to first page
5. Checkbox is no longer selected

In order to allow the user to combine species across multiple pages, the checkbox should remain checked.

**Comment by tranquanghuy0801** [comment]
Hi @nmcharlton , Can I work on this?
