### ISSUE TITLE
This planter's photo need rotation

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#987]
No.649

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/5744708/209035573-285bdbbc-d3db-41c8-85d2-242f2ef5aec5.png">

**Comment by dadiorchen** [comment]
Usually, how do we handle cases like this?

**Comment by nmcharlton** [comment]
We have a rotation button in the Edit Grower dialog. I've set the rotation for this Grower.
![image](https://user-images.githubusercontent.com/5558838/209077373-13823941-b167-4a29-94ed-476d2c751495.png)

**Comment by dadiorchen** [comment]
Nice mobile UI!
