### ISSUE TITLE
Verify: Refactor capture tagging UX

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#995]
The Verify tool side panel allows the user to apply any number of free-text tags to a capture at the point of verification (using "Additional tags"), but also forces them to select a "capture approval tag" from a fairly arbitrary radio button list.
In practice, verifiers almost always leave this option on the default "Simple leaf", rendering it fairly meaningless.

<img width="252" alt="Screenshot 2023-01-01 at 18 47 43" src="https://user-images.githubusercontent.com/5558838/210181603-a7a05094-1dc4-4d6b-9d0f-ba4633a57bcf.png">

A better UX may be the removal of the radio buttons and an enhancement to the "Additional tags" input to present common tags for quick selection (e.g., chips, checkboxes).

**Comment by rccm88** [comment]
Hi @nmcharlton, I want to work on this.

**Comment by Gabriellima784** [comment]
> rccm88

Hi @rccm88  i can work with you?

**Comment by rccm88** [comment]
@Gabriellima784 hey. Yeah, I don't see why not

**Comment by nmcharlton** [comment]
@rccm88 @Gabriellima784 If you need any guidance on this issue or have any questions, please reach out here or in Slack.

**Comment by rccm88** [comment]
@nmcharlton Nick, what would be these common tags to be suggested to users?

**Comment by Gabriellima784** [comment]
@rccm88 what is your profile in slack?

**Comment by rccm88** [comment]
> @rccm88 what is your profile in slack?

It's Raí Carvalho.

**Comment by nmcharlton** [comment]
I propose we use the existing radio buttons as the "common tags" mentioned above.

Looking at the production database, we have the following number of captures for each of the radio button tags:

Tag | Count
-- | --:
simple_leaf | 2,328,421
mangrove | 222,859
acacia_like | 97,766
fruit | 64,510
timber | 54,280
complex_leaf | 24,190
conifer | 5,252
palm | 1,389

While the vast majority stick with the default `simple_leaf`, there's a significant proportion using other tags. Therefore, retaining these as quick-add tags seems like a good idea.

**Comment by rccm88** [comment]
@nmcharlton Ok, will do that. 

One thing I noticed is that the backend does not accept a submition with no tags. It requires at least one tag (capture approval tag). This wasn't a problem before because "simple_leaf" was always selected.

I think a good solution would be to validate the additional tags input when users click the "submit" button to force users to include at least one tag.

I usually use the tool "yup" for that. Would that be ok?

**Comment by Gabriellima784** [comment]
@nmcharlton What if, in addition to correcting the tags, we also update the capture interface? Just like this, I
 will send image with more details in your slack 
![Refactory](https://user-images.githubusercontent.com/121263966/214443501-96efeeae-a9d1-4e9f-9ea6-3e11a67d7cce.png)

**Comment by nmcharlton** [comment]
> @nmcharlton Ok, will do that.
> 
> One thing I noticed is that the backend does not accept a submition with no tags. It requires at least one tag (capture approval tag). This wasn't a problem before because "simple_leaf" was always selected.
> 
> I think a good solution would be to validate the additional tags input when users click the "submit" button to force users to include at least one tag.
> 
> I usually use the tool "yup" for that. Would that be ok?

Let's remove the constraint on the API. I don't think there's any need to force the user to include a tag.
I'll raise an issue on the API.

**Comment by nmcharlton** [comment]
> > @nmcharlton Ok, will do that.
> > One thing I noticed is that the backend does not accept a submition with no tags. It requires at least one tag (capture approval tag). This wasn't a problem before because "simple_leaf" was always selected.
> > I think a good solution would be to validate the additional tags input when users click the "submit" button to force users to include at least one tag.
> > I usually use the tool "yup" for that. Would that be ok?
> 
> Let's remove the constraint on the API. I don't think there's any need to force the user to include a tag. I'll raise an issue on the API.

Actually, the backend does not impose any such constraint. The `POST /captures` endpoint doesn't include the capture tags, and to verify a capture without tags, we just wouldn't send the `POST /tags` message afterwards.

This statement in VerifyContext.js should mean we don't have to include any tags:
```
      if (approveAction.tags.length) {
        await api.createCaptureTags(capture.id, approveAction.tags);
      }
```

**Comment by rccm88** [comment]
@nmcharlton You're right. It was a frontend issue. I fixed it and created a pull request.
